BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Ce dont un DRESSEUR a besoin…\n"
	.string "Connaissances… Stratégie… Chance…\p"
	.string "Courage… Esprit… Courage… Et\n"
	.string "capacité… Eh bien, je suis prêt\p"
	.string "dans tous les sens ! Je serai\n"
	.string "imparable dans chaque bâtiment !\p"
	.string "Hein? POKéMON ? Qu'est-ce que c'est\n"
	.string "?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Connaissez-vous les FRONTIER BRAINS\n"
	.string "? C'est ainsi que SCOTT appelle les\p"
	.string "sept DRESSEURS spéciaux qui gèrent\n"
	.string "les sept installations de ZONE DE\p"
	.string "COMBAT.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Au BATTLE TOWER, une fille plus\n"
	.string "âgée m'a dit que j'avais beaucoup\p"
	.string "de talent pour me battre ! J'aime\n"
	.string "davantage les CONCOURS POKéMON !\p"
	.string "Mais je ne suis pas doué pour les\n"
	.string "CONCOURS ! Je suppose qu'avoir du\p"
	.string "talent et aimer quelque chose ne\n"
	.string "sont pas la même chose.$"
