PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPA : Salut, {PLAYER} ! Je viens de\n"
	.string "recevoir une BERRY très rare.\p"
	.string "J'aimerais que tu l'aies.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si vous voyez des BAIES pousser\n"
	.string "dans un sol limoneux, n'hésitez pas\p"
	.string "à les prendre. Mais assurez-vous de\n"
	.string "planter une BAIE au même endroit.\p"
	.string "C'est une simple courtoisie. Tiens,\n"
	.string "je vais partager ça avec vous.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "À votre apparence, vous devez être\n"
	.string "un DRESSEUR, non ? Les dresseurs\p"
	.string "font souvent en sorte que POKéMON\n"
	.string "tienne des BAIES. C'est à vous de\p"
	.string "décider si vous souhaitez cultiver\n"
	.string "des BAIES ou les utiliser.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "J'ai arrosé les plantes tous les\n"
	.string "jours. Ils ont fait pousser\p"
	.string "beaucoup de fleurs. Et ils m'ont\n"
	.string "aussi donné beaucoup de BAIES.\p"
	.string "Voici! Vous pouvez l'avoir !$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Je vais essayer très fort et faire\n"
	.string "des BAIES de différentes couleurs.\p"
	.string "J'espère que vous faites de gros\n"
	.string "efforts aussi !$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Je me demande quelle couleur de\n"
	.string "BAIES je vais chercher aujourd'hui\p"
	.string "?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "J'adore utiliser la machine BERRY\n"
	.string "CRUSH, donc je collectionne les\p"
	.string "BAIES. Je vais en partager un avec\n"
	.string "vous, si vous le souhaitez.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Vous devriez essayer la machine\n"
	.string "BERRY CRUSH avec vos amis.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quelle BAIE faut-il planter ?\n"
	.string "Devriez-vous utiliser ou accumuler\p"
	.string "des BAIES ? C'est amusant d'y\n"
	.string "penser.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "LES BAIES poussent en absorbant la\n"
	.string "lumière du soleil. Nous aidons les\p"
	.string "BAIES à pousser en les arrosant\n"
	.string "régulièrement. C'est une expression\p"
	.string "d'amour, n'est-ce pas ?$"

Route120_Text_YesYouUnderstand:
	.string "Oui oui. Vous comprenez ce que je\n"
	.string "veux dire. Tu devrais prendre ça.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Mais il est important de faire\n"
	.string "vos propres impressions, je\p"
	.string "suppose… Vous pouvez l'avoir.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Je pense que BERRY est rare.\n"
	.string "J'espère que vous l'élèverez avec\p"
	.string "amour.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "J'obtiendrai plus de BAIES du BERRY\n"
	.string "MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "En fin de compte… De la même\n"
	.string "manière que cela me convient\p"
	.string "parfaitement, une brise fraîche\n"
	.string "convient à la mer. Et vous, une\p"
	.string "BERRY vous va à merveille… Pourquoi\n"
	.string "devrait-il en être ainsi ?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Au fond… C'est parce que tu es un\n"
	.string "FORMATTHIEUEUR !$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "En fin de compte… Dans la mesure où\n"
	.string "la simplicité et la dignité me\p"
	.string "conviennent, les {POKEBLOCK} conviennent\n"
	.string "parfaitement aux POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Vous pouvez m'appeler le BERRY\n"
	.string "MASTER. Je rêve de remplir le monde\p"
	.string "de belles fleurs, alors je cultive\n"
	.string "des BAIES et les distribue à tout\p"
	.string "le monde. Vous en méritez un !$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Pourquoi être avare ? Prends-en un\n"
	.string "autre !$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "N'oubliez pas de visiter le magasin\n"
	.string "de fleurs JOLIE FLEUR près\p"
	.string "de RUSTBORO. Laissez les fleurs\n"
	.string "remplir le monde !$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "J'ai fini pour aujourd'hui. Reviens\n"
	.string "un autre jour. Laissez les fleurs\p"
	.string "remplir le monde !$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "La façon dont mon mari cultive des\n"
	.string "BAIES, oh, il est le meilleur au\p"
	.string "monde. Il me rend fier, ce qu'il\n"
	.string "fait. Au fait, mon enfant, as-tu\p"
	.string "entendu un bon dicton ces derniers\n"
	.string "temps ?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah ! Quelle parole remarquable !\n"
	.string "Inspirant, ça l'est ! Je veux que\p"
	.string "tu aies ça.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! C'est un bon dicton. Vous êtes\n"
	.string "tout à fait remarquable. Je veux\p"
	.string "que tu aies ça.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nos quatre petits-enfants devraient\n"
	.string "devenir plus accomplis que mon\p"
	.string "mari. La joie ne sort jamais de ma\n"
	.string "vie !$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Bonjour! Voici le fleuriste\n"
	.string "JOLIE FLEUR. Répandez des\p"
	.string "fleurs partout dans le monde !$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, souhaitez-vous en\n"
	.string "savoir plus sur BERRIES ?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Ton nom est? {PLAYER}{KUN}. C'est un\n"
	.string "joli nom. {PLAYER}{KUN},\p"
	.string "souhaitez-vous en savoir plus sur\n"
	.string "BERRIES ?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "LES BAIES poussent sur des arbres\n"
	.string "qui prospèrent uniquement dans un\p"
	.string "sol mou et limoneux. Si vous prenez\n"
	.string "des BAIES, assurez-vous d’en\p"
	.string "replanter une dans le sol limoneux.\n"
	.string "Une BAIE plantée va bientôt germer,\p"
	.string "devenir une plante, fleurir\n"
	.string "magnifiquement, puis faire pousser\p"
	.string "à nouveau des BAIES. Je veux voir\n"
	.string "le monde entier rempli de belles\p"
	.string "fleurs. C'est mon rêve. S'il vous\n"
	.string "plaît, aidez-moi, {PLAYER}{KUN}.\p"
	.string "Plantez des BAIES et apportez plus\n"
	.string "de fleurs au monde.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les fleurs apportent tellement de\n"
	.string "bonheur aux gens, n'est-ce pas ?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Bonjour! Plus vous accordez\n"
	.string "d’attention aux fleurs, plus elles\p"
	.string "s’épanouissent magnifiquement. Vous\n"
	.string "aimerez entretenir les fleurs. Je\p"
	.string "suis sur et certain. Vous pouvez\n"
	.string "avoir ça.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Pendant que les plants de BAIES\n"
	.string "poussent, arrosez-les avec le SEAU\p"
	.string "WAILMER. Oh, autre chose. Si vous\n"
	.string "ne cueillez pas les BAIES pendant\p"
	.string "un moment, elles tomberont au sol.\n"
	.string "Mais ils repousseront. N'est-ce pas\p"
	.string "génial ? C'est comme s'ils avaient\n"
	.string "la volonté de vivre.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "J'essaie d'être comme mes grandes\n"
	.string "sœurs. Moi aussi je fais pousser\p"
	.string "des fleurs ! Voici! C'est pour\n"
	.string "toi!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Vous pouvez planter une BAIE et la\n"
	.string "faire grandir, ou vous pouvez faire\p"
	.string "en sorte qu'un POKéMON la tienne.\n"
	.string "Mais maintenant, ils ont une\p"
	.string "machine qui mélange différentes\n"
	.string "BAIES et fabrique des bonbons pour\p"
	.string "POKéMON. Je veux aussi des\n"
	.string "bonbons.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Salut, quel est ton nom ? … … …  …\n"
	.string "… …  … … … D'accord. C'est bien! Je\p"
	.string "m'appelle KIRI. Ma maman et mon\n"
	.string "papa m'ont nommé ainsi pour que je\p"
	.string "grandisse en bonne santé et\n"
	.string "chaleureuse. C'est ce qu'ils\p"
	.string "souhaitaient. Vous pouvez en avoir\n"
	.string "un.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI vous offrira aussi cette BAIE\n"
	.string "! J'aime vraiment beaucoup !$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Je me demande quel genre de souhait\n"
	.string "est inclus dans votre nom.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Printemps, été, automne et hiver.\n"
	.string "Si vous êtes né au printemps,\p"
	.string "aimez-vous le printemps, et si vous\n"
	.string "êtes né en été, aimez-vous l'été ?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Puis KIRI est née en automne, donc\n"
	.string "j'adore l'automne ! Quelle saison\p"
	.string "aimez-vous?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh… Ce n'est pas grave… Il y a\n"
	.string "tellement de choses que je veux\p"
	.string "savoir…$"
