Route102_Text_CalvinIntro:
	.string "Si vous avez POKéMON avec vous,\n"
	.string "alors vous êtes un DRESSEUR POKéMON\p"
	.string "officiel ! Vous ne pouvez pas dire\n"
	.string "non à mon défi !$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, j'ai perdu… j'aurais dû\n"
	.string "entraîner davantage le mien…$"

Route102_Text_CalvinPostBattle:
	.string "Écoute, toi. Si tu es fort, tu\n"
	.string "aurais dû me le dire avant !$"

Route102_Text_CalvinRegister:
	.string "J'ai travaillé dur là-dessus depuis\n"
	.string "que je t'ai vu auparavant.\p"
	.string "J'aimerais te combattre à nouveau,\n"
	.string "alors peux-tu m'inscrire dans ton\p"
	.string "POKéNAV ?$"

Route102_Text_CalvinRegisterShort:
	.string "J'aimerais te combattre à nouveau,\n"
	.string "alors peux-tu m'inscrire dans ton\p"
	.string "POKéNAV ?$"

Route102_Text_CalvinRematchIntro:
	.string "Depuis que j'ai perdu contre toi,\n"
	.string "j'ai désespérément entraîné mon\p"
	.string "POKéMON. Vous ne pouvez pas dire\n"
	.string "non à mon défi !$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, j'ai perdu… Ma méthode\n"
	.string "d'entraînement n'est pas la bonne\p"
	.string "?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si tu veux devenir plus fort, je\n"
	.string "deviendrai plus fort aussi.$"

Route102_Text_AllenIntro:
	.string "Vous venez de devenir\n"
	.string "DRESSEUR ? Nous sommes tous\p"
	.string "les deux débutants !$"

Route102_Text_AllenDefeated:
	.string "Je t'ai appelé parce que je pensais\n"
	.string "pouvoir te battre…$"

Route102_Text_AllenPostBattle:
	.string "Je n'ai pas encore gagné une seule\n"
	.string "fois… J'aimerais gagner bientôt…$"

Route102_Text_RickIntro:
	.string "Hahah ! Nos regards se sont croisés\n"
	.string "! Je t'emmène avec mon BUG POKéMON\p"
	.string "!$"

Route102_Text_RickDefeated:
	.string "Aïe ! À terre et dehors !$"

Route102_Text_RickPostBattle:
	.string "Si vous croisez les yeux d'un\n"
	.string "DRESSEUR, vous devez relever un\p"
	.string "défi ! C'est une règle !$"

Route102_Text_TianaIntro:
	.string "Je vais continuer à gagner et viser\n"
	.string "à être le meilleur DRESSEUR.\p"
	.string "Aide-moi à faire avancer ma\n"
	.string "carrière !$"

Route102_Text_TianaDefeated:
	.string "J'ai fini par faire avancer ta\n"
	.string "carrière…$"

Route102_Text_TianaPostBattle:
	.string "Pour continuer à progresser, je\n"
	.string "vois que je dois attraper plus de\p"
	.string "POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Avez-vous ressenti l'attrait de\n"
	.string "notre parfum apaisant pour l'âme ?$"

Route103_Text_DaisyDefeated:
	.string "Vous n'avez pas été égaré par notre\n"
	.string "arôme…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromathérapie est une forme de\n"
	.string "guérison mentale qui fonctionne\p"
	.string "avec des parfums.$"

Route103_Text_AmyIntro:
	.string "AMY : Je m'appelle AMY. Et voici ma\n"
	.string "petite sœur LIV. Nous luttons\p"
	.string "ensemble !$"

Route103_Text_AmyDefeated:
	.string "AMY : Oh-oh, nous avons perdu.$"

Route103_Text_AmyPostBattle:
	.string "AMY : Vous devez penser à toutes\n"
	.string "sortes de choses lorsque vous vous\p"
	.string "battez contre deux DRESSEURS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY : Oh-oh, tu n'as qu'un seul\n"
	.string "POKéMON avec toi. Vous ne pouvez\p"
	.string "pas nous combattre comme ça.$"

Route103_Text_LivIntro:
	.string "LIV : Nous combattons ensemble\n"
	.string "comme une seule équipe.$"

Route103_Text_LivDefeated:
	.string "LIV : Oh, nous avons perdu, grande\n"
	.string "sœur…$"

Route103_Text_LivPostBattle:
	.string "LIV : On travaille parfaitement\n"
	.string "ensemble, moi et ma grande sœur…\p"
	.string "Mais on a quand même perdu…$"

Route103_Text_AmyLivRegister:
	.string "LIV : C'est vrai qu'on est bien\n"
	.string "meilleurs… C'est vrai ! Nous vous\p"
	.string "montrerons la prochaine fois !$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV : Si vous voulez nous\n"
	.string "affronter, vous devez avoir deux\p"
	.string "POKéMON ! Ce n'est pas juste si tu\n"
	.string "ne le fais pas !$"

Route103_Text_AmyRematchIntro:
	.string "AMY : Je m'appelle AMY. Et voici ma\n"
	.string "petite sœur LIV. Nous luttons\p"
	.string "ensemble !$"

Route103_Text_AmyRematchDefeated:
	.string "AMY : Aww, bouh ! Nous ne pouvions\n"
	.string "pas gagner à nouveau…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY : Vous devez penser à toutes\n"
	.string "sortes de choses lorsque vous vous\p"
	.string "battez contre deux DRESSEURS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY : Oh-oh, tu n'as qu'un seul\n"
	.string "POKéMON avec toi. Vous ne pouvez\p"
	.string "pas nous combattre comme ça.$"

Route103_Text_LivRematchIntro:
	.string "LIV : Nous combattons ensemble\n"
	.string "comme une seule équipe.$"

Route103_Text_LivRematchDefeated:
	.string "LIV : Awww, nous avons encore\n"
	.string "perdu… Grande sœur…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV : Nous travaillons parfaitement\n"
	.string "ensemble, moi et ma grande sœur…\p"
	.string "Mais pourquoi avons-nous encore\n"
	.string "perdu ?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV : Si vous voulez nous\n"
	.string "affronter, vous devez avoir deux\p"
	.string "POKéMON ! Ce n'est pas juste si tu\n"
	.string "ne le fais pas !$"

Route103_Text_AndrewIntro:
	.string "Waouh ! Ma ligne de pêche est toute\n"
	.string "emmêlée ! Je deviens frustré et\p"
	.string "méchant ! C'est ça! Combattez-moi\n"
	.string "!$"

Route103_Text_AndrewDefeated:
	.string "Waouh ! Perdu! Je suis encore plus\n"
	.string "ennuyé maintenant !$"

Route103_Text_AndrewPostBattle:
	.string "Gah, je suis toujours en colère…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mon POKéMON est délicieusement\n"
	.string "adorable ! Ne soyez pas timide, je\p"
	.string "vais vous montrer !$"

Route103_Text_MiguelDefeated:
	.string "Oh mon Dieu! Mon POKéMON chéri!$"

Route103_Text_MiguelPostBattle:
	.string "Mon délicieux POKéMON a l'air chéri\n"
	.string "même lorsqu'il s'évanouit !$"

Route103_Text_MiguelRegister:
	.string "Je vais vous demander de venir voir\n"
	.string "à nouveau mon délicieux POKéMON !$"

Route103_Text_MiguelRematchIntro:
	.string "Salut toi! Mon POKéMON\n"
	.string "délicieusement adorable est devenu\p"
	.string "encore plus chéri !$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh! Mon POKéMON chéri!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Plus je passe du temps avec lui,\n"
	.string "plus mon POKéMON devient adorable.$"

Route103_Text_PeteIntro:
	.string "Ce genre de distance… Tu devrais\n"
	.string "juste la nager !$"

Route103_Text_PeteDefeated:
	.string "Oh, ça va !$"

Route103_Text_PetePostBattle:
	.string "Oh, je comprends d'où tu viens\n"
	.string "maintenant. Si j'avais un POKéMON\p"
	.string "aussi fidèle, je voudrais surfer\n"
	.string "dessus aussi !$"

Route103_Text_IsabelleIntro:
	.string "Regardez où vous allez! On va\n"
	.string "s'écraser !$"

Route103_Text_IsabelleDefeated:
	.string "Gémir…$"

Route103_Text_IsabellePostBattle:
	.string "Je suis un mauvais nageur alors je\n"
	.string "m'entraînais… Désolé d'avoir failli\p"
	.string "t'écraser.$"

Route103_Text_RhettIntro:
	.string "Waouh ! Comment es-tu entré dans un\n"
	.string "espace aussi petit ?$"

Route103_Text_RhettDefeated:
	.string "Waouh ! L'enfant peut rocker !$"

Route103_Text_RhettPostBattle:
	.string "Aimez-vous les espaces exigus comme\n"
	.string "celui-ci ?$"

Route103_Text_MarcosIntro:
	.string "Les gémissements de ma guitare vous\n"
	.string "ont-ils attiré ?$"

Route103_Text_MarcosDefeated:
	.string "Mon one-man show est ruiné…$"

Route103_Text_MarcosPostBattle:
	.string "Je jouais de ma guitare là où il y\n"
	.string "avait peu de monde, mais beaucoup\p"
	.string "de fans se sont rassemblés. Heh,\n"
	.string "peut-être que je devrais devenir\p"
	.string "pro.$"

Route104_Text_GinaIntro:
	.string "GINA : D'accord, battons-nous avec\n"
	.string "notre POKéMON !$"

Route104_Text_GinaDefeat:
	.string "GINA : Perdre me bouleverse !$"

Route104_Text_GinaPostBattle:
	.string "GINA : Tu es forte ! Nous devons\n"
	.string "nous entraîner beaucoup plus !$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA : Ah ? Un seul POKéMON ?\n"
	.string "Alors, nous ne nous battons pas\p"
	.string "avec vous. S'il n'y a qu'un seul\n"
	.string "POKéMON, il sera solitaire. Ce\p"
	.string "n'est pas sympa.$"

Route104_Text_MiaIntro:
	.string "MIA : Nous sommes jumeaux, donc\n"
	.string "nous combattons POKéMON ensemble.$"

Route104_Text_MiaDefeat:
	.string "MIA : Nous nous sommes battus\n"
	.string "ensemble, mais nous avons tous les\p"
	.string "deux perdu…$"

Route104_Text_MiaPostBattle:
	.string "MIA : Nous entraînerons davantage\n"
	.string "nos POKéMON et serons forts comme\p"
	.string "vous.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA : Tu veux te battre avec nous ?\n"
	.string "C'est un grand non-non si vous\p"
	.string "n'avez pas deux POKéMON avec vous.\n"
	.string "Nous sommes trop forts pour vous !$"

Route104_Text_IvanIntro:
	.string "Pourquoi garder cela secret ? Je\n"
	.string "suis l'expert POKéMON EAU ! Hein?\p"
	.string "Tu ne me connais pas ?$"

Route104_Text_IvanDefeat:
	.string "Je pensais que je n'étais pas trop\n"
	.string "mauvais, si je puis dire, mais je\p"
	.string "suppose que non… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "Moi aussi, je me suis mis à la\n"
	.string "pêche. J'ai oublié que je devais\p"
	.string "augmenter mon POKéMON…$"

Route104_Text_BillyIntro:
	.string "Laisser des empreintes dans le\n"
	.string "sable, c'est tellement amusant !$"

Route104_Text_BillyDefeat:
	.string "Waah ! J'ai du sable dans mes\n"
	.string "patins ! Ils sont tous crasseux !$"

Route104_Text_BillyPostBattle:
	.string "J'ai envie de laisser mes\n"
	.string "empreintes dans le sable partout,\p"
	.string "mais elles disparaissent vite…$"

Route104_Text_HaleyIntro:
	.string "Dois-je… Ou ne devrais-je pas ?\n"
	.string "D'accord, bien sûr, je vais me\p"
	.string "battre !$"

Route104_Text_HaleyDefeat:
	.string "Je n'aurais pas dû me battre…$"

Route104_Text_HaleyPostBattle:
	.string "Si vous êtes confronté à une\n"
	.string "décision et que vous laissez\p"
	.string "quelqu'un d'autre choisir à votre\n"
	.string "place, vous la regretterez, quelle\p"
	.string "que soit la tournure des choses.$"

Route104_Text_HaleyRegister1:
	.string "Tu es fort, mais dois-je t'inscrire\n"
	.string "dans mon POKéNAV ? Peut-être que je\p"
	.string "ne devrais pas… D'accord, bien sûr,\n"
	.string "je vais vous inscrire !$"

Route104_Text_HaleyRegister2:
	.string "Tu es fort, mais dois-je t'inscrire\n"
	.string "dans mon POKéNAV ? Peut-être que je\p"
	.string "ne devrais pas… D'accord, bien sûr,\n"
	.string "je vais vous inscrire !$"

Route104_Text_HaleyRematchIntro:
	.string "Allez, bats-toi avec moi !$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh… je pensais que je pourrais\n"
	.string "gagner…$"

Route104_Text_HaleyPostRematch:
	.string "J'ai pris la décision de me battre\n"
	.string "pour pouvoir accepter cette perte\p"
	.string "avec grâce. Je suis toujours\n"
	.string "contrarié d'avoir perdu !$"

Route104_Text_WinstonIntro:
	.string "Oh, bien sûr, j'accepterai votre\n"
	.string "défi. J'ai beaucoup d'argent.$"

Route104_Text_WinstonDefeat:
	.string "Pourquoi n'ai-je pas pu gagner ?$"

Route104_Text_WinstonPostBattle:
	.string "Il y a des choses que l’argent ne\n"
	.string "peut pas acheter. C'est POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hein ? Ah, vous avez obtenu un\n"
	.string "POKéNAV. Je vous inscrirai avec\p"
	.string "plaisir. Après tout, j'ai beaucoup\n"
	.string "d'argent.$"

Route104_Text_WinstonRegister2:
	.string "Hein ? Ah, vous avez obtenu un\n"
	.string "POKéNAV. Je vous inscrirai avec\p"
	.string "plaisir. Après tout, j'ai beaucoup\n"
	.string "d'argent.$"

Route104_Text_WinstonRematchIntro:
	.string "Après avoir perdu contre toi, j'ai\n"
	.string "appris beaucoup de choses sur\p"
	.string "POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "J'ai encore perdu ? Pourquoi\n"
	.string "n'ai-je pas pu gagner ?$"

Route104_Text_WinstonPostRematch:
	.string "Je suis fabuleusement riche, mais\n"
	.string "je n'arrive pas à gagner sur\p"
	.string "POKéMON… C'est tellement profond,\n"
	.string "le monde de POKéMON…$"

Route104_Text_CindyIntro:
	.string "Nous devions être destinés à nous\n"
	.string "rencontrer. Puis-je vous demander\p"
	.string "une bataille ?$"

Route104_Text_CindyDefeat:
	.string "Oh, mon Dieu !$"

Route104_Text_CindyPostBattle:
	.string "“ Bonjour ” est le début de “ au\n"
	.string "revoir ”. J'espère que nous nous\p"
	.string "reverrons.$"

Route104_Text_CindyRegister1:
	.string "Bonjour, nous nous retrouvons. Nous\n"
	.string "semblons être rapprochés.\p"
	.string "Inscrivons-nous les uns aux autres\n"
	.string "dans nos POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "Nous devrions commémorer à quel\n"
	.string "point nous semblons être attirés\p"
	.string "les uns par les autres.\n"
	.string "Inscrivons-nous les uns aux autres\p"
	.string "dans nos POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Bonjour, nous nous retrouvons.\n"
	.string "Puis-je vous demander une bataille\p"
	.string "?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, mon… j'ai fait de mon mieux…$"

Route104_Text_CindyPostRematch:
	.string "“ Bonjour ” est le début de “ au\n"
	.string "revoir ”. J'espère que nous nous\p"
	.string "reverrons.$"

Route104_Text_DarianIntro:
	.string "J'ai repêché un POKéMON à l'air\n"
	.string "coriace ! Il a ce côté magique !\p"
	.string "Cela a sûrement l’air difficile,\n"
	.string "oui !$"

Route104_Text_DarianDefeat:
	.string "Qu'est-ce que…$"

Route104_Text_DarianPostBattle:
	.string "Hé, MAGIKARP, tu n'es certainement\n"
	.string "pas à la hauteur de ton nom,\p"
	.string "n'est-ce pas ?$"

Route105_Text_FosterIntro:
	.string "Il est censé y avoir un rocher\n"
	.string "mystique par ici. En savez-vous\p"
	.string "quelque chose ?$"

Route105_Text_FosterDefeated:
	.string "Je pensais trop à ce rocher, alors\n"
	.string "que mon POKéMON restait faible…$"

Route105_Text_FosterPostBattle:
	.string "Je peux passer des heures et des\n"
	.string "heures à regarder un joli rocher\p"
	.string "sans m'ennuyer.$"

Route105_Text_LuisIntro:
	.string "Ouf! J'avais peur qu'un enfant se\n"
	.string "noie quand je t'ai vu. Vous semblez\p"
	.string "aller bien, alors que dites-vous\n"
	.string "d'une bataille ?$"

Route105_Text_LuisDefeated:
	.string "Profondeur... Profondeur...$"

Route105_Text_LuisPostBattle:
	.string "Si vous vous noyez, le signal est\n"
	.string "d’agiter un bras vers la plage.$"

Route105_Text_DominikIntro:
	.string "Nager dans la mer d’un bleu\n"
	.string "profond… C’est le meilleur !$"

Route105_Text_DominikDefeated:
	.string "J'ai perdu… Maintenant, je me sens\n"
	.string "déprimé…$"

Route105_Text_DominikPostBattle:
	.string "Pourquoi la mer est-elle bleue ?\n"
	.string "J'ai appris cela au MUSÉE de\p"
	.string "SLATEPORT, mais j'ai oublié.$"

Route105_Text_BeverlyIntro:
	.string "Mon corps se sent plus léger dans\n"
	.string "l'eau. C'est comme si j'étais\p"
	.string "devenu plus mince !$"

Route105_Text_BeverlyDefeated:
	.string "Je flotte…$"

Route105_Text_PostBattle:
	.string "Votre poids corporel est réduit à\n"
	.string "seulement un dixième dans l’eau.\p"
	.string "Cela me ferait… Oups ! Je ne te dis\n"
	.string "pas mon poids !$"

Route105_Text_ImaniIntro:
	.string "Le ciel bleu, bleu… La vaste mer…\n"
	.string "C'est si paisible…$"

Route105_Text_ImaniDefeated:
	.string "J'ai perdu en me prélassant !$"

Route105_Text_ImaniPostBattle:
	.string "Je veux qu'on me dise que je me\n"
	.string "détends. Rire.$"

Route105_Text_AndresIntro:
	.string "Je suis convaincu que la mer nous\n"
	.string "cache des secrets.$"

Route105_Text_AndresDefeated:
	.string "Oui… je ne suis pas doué pour me\n"
	.string "battre…$"

Route105_Text_AndresPostBattle:
	.string "Je suis sûr qu'il y a de nombreux\n"
	.string "secrets à découvrir dans les mers\p"
	.string "du monde. Je veux tous les trouver\n"
	.string "!$"

Route105_Text_AndresRegister:
	.string "Hein? Je suis si faible, mais tu es\n"
	.string "prêt à m'inscrire dans ton POKéNAV\p"
	.string "?$"

Route105_Text_AndresRematchIntro:
	.string "Je t'ai dit que j'étais faible…\n"
	.string "Es-tu sûr de vouloir faire ça ?$"

Route105_Text_AndresRematchDefeated:
	.string "Oui… je ne pensais pas pouvoir\n"
	.string "gagner.$"

Route105_Text_AndresRematchPostBattle:
	.string "Je suis peut-être faible au combat,\n"
	.string "mais ma volonté d'explorer ne peut\p"
	.string "être surpassée. Je voyagerai sur\n"
	.string "les mers du monde entier !$"

Route105_Text_JosueIntro:
	.string "Je suis épuisé par la natation. Je\n"
	.string "n'y suis tout simplement pas\p"
	.string "habitué. J'ai besoin d'une bataille\n"
	.string "pour changer de rythme !$"

Route105_Text_JosueDefeated:
	.string "J'ai perdu parce que j'ai combattu\n"
	.string "en mer.$"

Route105_Text_JosuePostBattle:
	.string "Ouais, pour moi, le ciel se marie\n"
	.string "bien mieux que la mer.$"

Route106_Text_ElliotIntro:
	.string "Que préférez-vous, pêcher en mer ou\n"
	.string "en ruisseau ?$"

Route106_Text_ElliotDefeated:
	.string "Comme à la pêche au gros, j'ai\n"
	.string "perdu de façon spectaculaire !$"

Route106_Text_ElliotPostBattle:
	.string "La pêche est la meilleure, que ce\n"
	.string "soit en mer ou en ruisseau. Vous\p"
	.string "êtes d'accord avec moi, n'est-ce\n"
	.string "pas ?$"

Route106_Text_ElliotRegister:
	.string "La pêche, c'est bien, mais les\n"
	.string "combats aussi. Si cela ne vous\p"
	.string "dérange pas, pouvons-nous nous\n"
	.string "revoir ?$"

Route106_Text_ElliotRematchIntro:
	.string "J'ai attrapé un tas de POKéMON en\n"
	.string "pêchant. Je vais vous montrer une\p"
	.string "bataille impressionnante !$"

Route106_Text_ElliotRematchDefeated:
	.string "J'ai encore perdu de façon\n"
	.string "spectaculaire !$"

Route106_Text_ElliotRematchPostBattle:
	.string "Gagner ou perdre, les POKéMON sont\n"
	.string "les meilleurs ! Vous êtes d'accord\p"
	.string "avec moi, n'est-ce pas ?$"

Route106_Text_NedIntro:
	.string "Que font les gens s’ils ont besoin\n"
	.string "d’aller aux toilettes ? Que se\p"
	.string "passe-t-il si ma tige en accroche\n"
	.string "une grosse pendant que je suis dans\p"
	.string "la salle de bain ? Je ne peux tout\n"
	.string "simplement pas y aller…$"

Route106_Text_NedDefeated:
	.string "J'ai perdu parce que j'essaie de ne\n"
	.string "pas aller aux toilettes…$"

Route106_Text_NedPostBattle:
	.string "Oh non! J'ai le sentiment que je\n"
	.string "vais en attraper un gros !$"

Route106_Text_DouglasIntro:
	.string "Hahahah ! Je suis un mauvais\n"
	.string "coureur, mais dans l'eau, tu ne\p"
	.string "peux pas m'attraper !$"

Route106_Text_DouglasDefeated:
	.string "J'abandonne !$"

Route106_Text_DouglasPostBattle:
	.string "Je ne perdrais pas dans une course\n"
	.string "de natation…$"

Route106_Text_KylaIntro:
	.string "La mer est mon jardin. Je ne vais\n"
	.string "pas y aller doucement parce que tu\p"
	.string "es un enfant !$"

Route106_Text_KylaDefeated:
	.string "Aurais-tu été doux avec moi, par\n"
	.string "hasard ?$"

Route106_Text_KylaPostBattle:
	.string "Dériver au gré des vagues… J'adore\n"
	.string "ça ! Pourquoi ne pas essayer ?$"

Route107_Text_DarrinIntro:
	.string "Bâillement… J'ai dû m'endormir\n"
	.string "pendant que je dérivais dans les\p"
	.string "vagues.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, j'ai perdu… je vais faire\n"
	.string "une sieste, je pense…$"

Route107_Text_DarrinPostBattle:
	.string "Flotter et se laisser bercer par\n"
	.string "les vagues, c'est comme dormir dans\p"
	.string "un lit moelleux et confortable.$"

Route107_Text_TonyIntro:
	.string "La mer est comme mon jardin.\n"
	.string "Battons-nous !$"

Route107_Text_TonyDefeated:
	.string "J'ai perdu sur mon terrain… je suis\n"
	.string "sous le choc !$"

Route107_Text_TonyPostBattle:
	.string "Je nage dans les mers avec un cœur\n"
	.string "plein de rêves… C'est une chanson !\p"
	.string "Quoi qu'il en soit, je nage\n"
	.string "encore.$"

Route107_Text_TonyRegister:
	.string "Vous m'avez choqué jusqu'aux os !\n"
	.string "Eh bien, pour ne pas m'oublier…$"

Route107_Text_TonyRematchIntro:
	.string "Nageant dans la grande et vaste\n"
	.string "mer, mon POKéMON est devenu plus\p"
	.string "fort !$"

Route107_Text_TonyRematchDefeated:
	.string "Quel choc! Mon POKéMON est devenu\n"
	.string "plus fort, mais je suis resté\p"
	.string "faible en tant qu'DRESSEUR !$"

Route107_Text_TonyRematchPostBattle:
	.string "Ce que vous apprenez au combat fait\n"
	.string "de vous un DRESSEUR plus fort. Les\p"
	.string "vagues m'ont appris ça.$"

Route107_Text_DeniseIntro:
	.string "Connaissez-vous une petite ville\n"
	.string "appelée DEWFORD ?$"

Route107_Text_DeniseDefeated:
	.string "Je déteste ça !$"

Route107_Text_DenisePostBattle:
	.string "Un dicton étrange devient vraiment\n"
	.string "à la mode au DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Voulais-tu me combattre ? Bien sûr,\n"
	.string "je viendrai avec toi !$"

Route107_Text_BethDefeated:
	.string "Je n'étais pas assez bien pour\n"
	.string "toi.$"

Route107_Text_BethPostBattle:
	.string "Je pense que tu vas continuer à\n"
	.string "t'améliorer. J'y vais aussi !$"

Route107_Text_LisaIntro:
	.string "LISA : Nous vous mettons au défi en\n"
	.string "tant que sœur et frère !$"

Route107_Text_LisaDefeated:
	.string "LISA : Génial. Vous êtes dans une\n"
	.string "classe différente de durs.$"

Route107_Text_LisaPostBattle:
	.string "LISA : As-tu des amis qui iraient à\n"
	.string "la plage avec toi ?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA : Si vous voulez combattre\n"
	.string "avec nous, apportez plus de\p"
	.string "POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY : Nous combattons toujours\n"
	.string "POKéMON, moi et ma sœur. Je perds\p"
	.string "toujours, mais nous pouvons te\n"
	.string "battre 2 contre 2 !$"

Route107_Text_RayDefeated:
	.string "RAY : Wowee, tu es à un niveau plus\n"
	.string "élevé que nous !$"

Route107_Text_RayPostBattle:
	.string "RAY : Ma sœur m'a donné mon\n"
	.string "POKéMON. Je l'ai élevé, et\p"
	.string "maintenant c'est mon partenaire\n"
	.string "important !$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY : Si tu veux nous affronter, va\n"
	.string "apporter encore quelques POKéMON !$"

Route107_Text_CamronIntro:
	.string "Je suis en plein triathlon, mais je\n"
	.string "ne suis pas du tout fatigué !$"

Route107_Text_CamronDefeated:
	.string "Cela m'a épuisé…$"

Route107_Text_CamronPostBattle:
	.string "Il me reste encore à nager et à\n"
	.string "courir après ça. Est-ce que je vais\p"
	.string "bien ?$"

Route108_Text_JeromeIntro:
	.string "Mon rêve est de nager dans les sept\n"
	.string "mers du monde !$"

Route108_Text_JeromeDefeated:
	.string "Je ne pourrai pas nager dans les\n"
	.string "sept mers comme ça…$"

Route108_Text_JeromePostBattle:
	.string "Jouer avec des POKéMON marins fait\n"
	.string "partie des plaisirs de la baignade\p"
	.string "!$"

Route108_Text_MatthewIntro:
	.string "Ohé! Allez-vous aussi au EPAVE ?$"

Route108_Text_MatthewDefeated:
	.string "Je coule! Profondeur...\n"
	.string "Profondeur...$"

Route108_Text_MatthewPostBattle:
	.string "Certaines personnes entrent même à\n"
	.string "l’intérieur de ce EPAVE.$"

Route108_Text_TaraIntro:
	.string "Mon petit ami menteur m'a dit que\n"
	.string "j'étais superbe en bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, bouh !$"

Route108_Text_TaraPostBattle:
	.string "Même si c'est un mensonge, j'aime\n"
	.string "qu'on me dise que je suis superbe…\p"
	.string "Nous, les filles, sommes si\n"
	.string "complexes…$"

Route108_Text_MissyIntro:
	.string "J'adore la mer! J'oublie tous mes\n"
	.string "soucis quand je nage !$"

Route108_Text_MissyDefeated:
	.string "Quand je perds une bataille, je\n"
	.string "suis complètement stressé !$"

Route108_Text_MissyPostBattle:
	.string "Évacuez votre stress en nageant !\n"
	.string "C'est tellement sain !$"

Route108_Text_CoryIntro:
	.string "J'adore les POKéMON de type EAU.\n"
	.string "J'aime aussi les autres POKéMON !$"

Route108_Text_CoryDefeated:
	.string "Ouah! J'ai perdu! Ouah! Waouh !$"

Route108_Text_CoryPostBattle:
	.string "Crier, ça me fait du bien ! Ça me\n"
	.string "remonte le moral !$"

Route108_Text_CoryRegister:
	.string "J'aime aussi les DRESSEURS\n"
	.string "coriaces ! Inscrivez-moi dans votre\p"
	.string "POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Gagner ou perdre, j'adore me battre\n"
	.string "en mer !$"

Route108_Text_CoryRematchDefeated:
	.string "Ouah! J'ai encore perdu ! Ouah!\n"
	.string "Waouh !$"

Route108_Text_CoryRematchPostBattle:
	.string "Si vous êtes confronté à un défi,\n"
	.string "essayez de crier à la mer !$"

Route108_Text_CarolinaIntro:
	.string "Je suis extrêmement fier de mon\n"
	.string "POKéMON. Nous allons vous montrer\p"
	.string "une bataille rapide !$"

Route108_Text_CarolinaDefeated:
	.string "Ce n'était pas mignon du tout.$"

Route108_Text_CarolinaPostBattle:
	.string "Puisque je suis en mer comme ça, ça\n"
	.string "ne me dérangerait pas d'enfiler un\p"
	.string "maillot de bain rose à froufrous…$"

Route109_Text_DavidIntro:
	.string "Salut ! Regardez mes abdos ciselés\n"
	.string "! C'est ce que vous appelez “\p"
	.string "couper ” !$"

Route109_Text_DavidDefeated:
	.string "Aiyah ! Échoué !$"

Route109_Text_DavidPostBattle:
	.string "Salut ! Mes abdos sculptés n'ont\n"
	.string "rien à voir avec les combats\p"
	.string "POKéMON !$"

Route109_Text_AliceIntro:
	.string "Êtes-vous bien protégé contre le\n"
	.string "soleil?$"

Route109_Text_AliceDefeated:
	.string "Aïe, aïe, aïe !$"

Route109_Text_AlicePostBattle:
	.string "Les joues sont les plus sujettes\n"
	.string "aux brûlures !$"

Route109_Text_HueyIntro:
	.string "J'ai jeté l'ancre dans des ports du\n"
	.string "monde entier, mais SLATEPORT est le\p"
	.string "meilleur.$"

Route109_Text_HueyDefeated:
	.string "Tu es le meilleur !$"

Route109_Text_HueyPostBattle:
	.string "Dans le meilleur port se trouvait\n"
	.string "le meilleur DRESSEUR…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp… Bataille ? Avec moi ?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh… Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Je suis généralement plus fort que\n"
	.string "ça ! J'ai juste le mal de mer comme\p"
	.string "un chien ! Je suis un MARIN, mais…$"

Route109_Text_RickyIntro:
	.string "J'ai soif… Je pourrais aller boire\n"
	.string "un SODA POP au SEASHORE HOUSE…$"

Route109_Text_RickyDefeated:
	.string "Gémir…$"

Route109_Text_RickyPostBattle:
	.string "Je commence à avoir faim… Ma\n"
	.string "chambre à air ressemble à un\p"
	.string "beignet géant…$"

Route109_Text_RickyRegister:
	.string "Auras-tu un autre match avec moi\n"
	.string "quand je n'aurai pas toute soif ?$"

Route109_Text_RickyRematchIntro:
	.string "J'ai faim, mais j'ai assez de peps\n"
	.string "en moi pour une bataille !$"

Route109_Text_RickyRematchDefeated:
	.string "J'ai perdu… C'est parce que j'ai\n"
	.string "faim…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quand on mange sur une plage, tout\n"
	.string "semble avoir un peu meilleur goût.$"

Route109_Text_LolaIntro:
	.string "Un parasol ne ressemble-t-il pas à\n"
	.string "une fleur géante ?$"

Route109_Text_LolaDefeated:
	.string "Maman !$"

Route109_Text_LolaPostBattle:
	.string "Si vous regardez la plage vue du\n"
	.string "ciel, elle ressemble à un grand\p"
	.string "jardin fleuri !$"

Route109_Text_LolaRegister:
	.string "Moi? Je suis ici tous les jours !$"

Route109_Text_LolaRematchIntro:
	.string "Je ne perdrai plus contre toi !\n"
	.string "C'est pour ça que j'ai ma chambre à\p"
	.string "air !$"

Route109_Text_LolaRematchDefeated:
	.string "Maman !$"

Route109_Text_LolaRematchPostBattle:
	.string "Si j'ai une chambre à air, la\n"
	.string "gentillesse de mon POKéMON et moi\p"
	.string "augmente !$"

Route109_Text_AustinaIntro:
	.string "Je ne peux pas nager sans ma\n"
	.string "chambre à air, mais je ne perdrai\p"
	.string "pas à POKéMON !$"

Route109_Text_AustinaDefeated:
	.string "Ai-je perdu parce que j'ai une\n"
	.string "chambre à air ?$"

Route109_Text_AustinaPostBattle:
	.string "Ma chambre à air est un article de\n"
	.string "mode. Je ne peux pas être vu sans.$"

Route109_Text_GwenIntro:
	.string "Salut, grand DRESSEUR.\n"
	.string "Veux-tu te battre avec moi ?$"

Route109_Text_GwenDefeated:
	.string "Oh, tu es fort.$"

Route109_Text_GwenPostBattle:
	.string "Comment es-tu devenu si fort ?$"

Route109_Text_CarterIntro:
	.string "Wahahah ! Ce mec va s'en prendre\n"
	.string "une grosse !$"

Route109_Text_CarterDefeated:
	.string "Ce mec vient d'en perdre un…$"

Route109_Text_CarterPostBattle:
	.string "Ce mec pense que tu es un grand.\n"
	.string "Non, tu es un grand futur !$"

Route109_Text_PaulIntro:
	.string "PAUL : Eh bien, c'est un\n"
	.string "casse-tête. J'aimerais que tu ne\p"
	.string "perturbes pas notre précieux temps\n"
	.string "ensemble.$"

Route109_Text_PaulDefeated:
	.string "PAUL : Eh bien, j'abandonne.$"

Route109_Text_PaulPostBattle:
	.string "PAUL : Eh bien, ne dis à personne\n"
	.string "que nous sommes là. Ceci n'est que\p"
	.string "notre monde privé à deux !$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL : Nous sommes totalement,\n"
	.string "profondément amoureux. C'est\p"
	.string "pourquoi nous menons nos batailles\n"
	.string "POKéMON ensemble.$"

Route109_Text_MelIntro:
	.string "MEL : Nous sommes totalement\n"
	.string "amoureux. Notre romance réchauffe\p"
	.string "tout HOENN !$"

Route109_Text_MelDefeated:
	.string "MEL : Nous avons perdu, et c'est de\n"
	.string "ma faute ! PAUL va me détester !$"

Route109_Text_MelPostBattle:
	.string "MEL : Euh, PAUL, tu es en colère\n"
	.string "contre moi ? S'il vous plaît, ne\p"
	.string "soyez pas en colère.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL : Nous sommes profondément et\n"
	.string "véritablement amoureux. C'est\p"
	.string "pourquoi nous menons nos batailles\n"
	.string "POKéMON ensemble.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah ! Voir? Ma chambre à air est\n"
	.string "ronde !$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh ! Dommage !$"

Route109_Text_ChandlerPostBattle:
	.string "Après t'avoir montré ma chambre à\n"
	.string "air ronde aussi…$"

Route109_Text_HaileyIntro:
	.string "Je ne sais pas nager, alors je fais\n"
	.string "semblant de nager.$"

Route109_Text_HaileyDefeated:
	.string "Je le pensais! Je ne pensais pas\n"
	.string "que nous pourrions gagner.$"

Route109_Text_HaileyPostBattle:
	.string "Quand j'apprendrai à nager, je\n"
	.string "pense que mon POKéMON deviendra\p"
	.string "plus résistant.$"

Route109_Text_ElijahIntro:
	.string "Pour un gars aussi macho que moi,\n"
	.string "ce genre de POKéMON est le match\p"
	.string "parfait !$"

Route109_Text_ElijahDefeated:
	.string "Je suis cool même dans la défaite,\n"
	.string "hein ?$"

Route109_Text_ElijahPostBattle:
	.string "Pour un gars aussi macho que moi,\n"
	.string "un porto est le cadre idéal ! Je\p"
	.string "suppose que je vais me diriger vers\n"
	.string "SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Waouh ! Regarde ça! Je suppose que\n"
	.string "vous n'êtes pas habitué aux courses\p"
	.string "de BIKE.$"

Route110_Text_JacobDefeated:
	.string "Waouh ! Mes freins sont tombés en\n"
	.string "panne !$"

Route110_Text_JacobPostBattle:
	.string "Les crevaisons et les problèmes de\n"
	.string "freins peuvent provoquer des\p"
	.string "blessures graves ! Inspectez votre\n"
	.string "VÉLO pour déceler des problèmes !$"

Route110_Text_AnthonyIntro:
	.string "Yo, toi ! Pouvez-vous suivre ma\n"
	.string "vitesse ?$"

Route110_Text_AnthonyDefeated:
	.string "Crash et brûle !$"

Route110_Text_AnthonyPostBattle:
	.string "La vitesse seule ne me permettra\n"
	.string "pas de gagner sur POKéMON. Je dois\p"
	.string "reconsidérer cela…$"

Route110_Text_BenjaminIntro:
	.string "Pas de panique si votre VELO roule\n"
	.string "vite !$"

Route110_Text_BenjaminDefeated:
	.string "Je ne devrais pas paniquer pendant\n"
	.string "les combats POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "Il n'y a pas lieu de paniquer ou de\n"
	.string "stresser. Allez-y doucement. Il\p"
	.string "reste beaucoup de temps.$"

Route110_Text_BenjaminRegister:
	.string "Je vais continuer à bosser sans\n"
	.string "stresser. Faites-moi signe si vous\p"
	.string "êtes d'humeur.$"

Route110_Text_BenjaminRematchIntro:
	.string "Tu ne vas pas un peu trop vite ?\n"
	.string "Allez-y doucement et battons-nous.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Je n'ai pas paniqué, mais j'ai\n"
	.string "quand même perdu…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Il n'y a pas lieu de paniquer ou de\n"
	.string "stresser. Allez-y doucement. Il\p"
	.string "reste beaucoup de temps.$"

Route110_Text_AbigailIntro:
	.string "Le triathlon est extrêmement dur.\n"
	.string "Vous devez compléter les trois\p"
	.string "épreuves de natation, de cyclisme\n"
	.string "et de course à pied.$"

Route110_Text_AbigailDefeated:
	.string "Les combats POKéMON sont également\n"
	.string "difficiles !$"

Route110_Text_AbigailPostBattle:
	.string "Je suis épuisé, j'ai donc besoin\n"
	.string "d'une pause. Il est important de se\p"
	.string "reposer correctement.$"

Route110_Text_AbigailRegister:
	.string "Tu sais que je t'aime! Faisons une\n"
	.string "revanche sur CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "N'est-ce pas sympa de se battre en\n"
	.string "faisant du vélo ?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow… Comment as-tu pu être si fort\n"
	.string "?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Vouliez-vous obtenir un record ? Je\n"
	.string "suis désolé si je t'ai retenu !$"

Route110_Text_JasmineIntro:
	.string "J'ai roulé sans m'arrêter. Mes\n"
	.string "cuisses sont comme des rochers !$"

Route110_Text_JasmineDefeated:
	.string "Je m'inquiète des crampes\n"
	.string "musculaires…$"

Route110_Text_JasminePostBattle:
	.string "Oh, tu as des BADGES GYM ? Pas\n"
	.string "étonnant que tu sois si fort !$"

Route110_Text_EdwardIntro:
	.string "J'avais prévu vos intentions ! Je\n"
	.string "ne peux pas perdre !$"

Route110_Text_EdwardDefeated:
	.string "Je n'ai pas réussi à prophétiser ma\n"
	.string "propre disparition !$"

Route110_Text_EdwardPostBattle:
	.string "Je vois ton avenir… Hmm… Je vois\n"
	.string "une lumière brillante…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha ! Je vais vous éblouir\n"
	.string "avec mes merveilles !$"

Route110_Text_JaclynDefeated:
	.string "J'ai merveilleusement perdu !$"

Route110_Text_JaclynPostBattle:
	.string "Vous avez réussi à gagner\n"
	.string "uniquement parce que c'était une\p"
	.string "merveille ! Oui, une merveille ! Ne\n"
	.string "pensez pas que vous pouvez gagner\p"
	.string "tout le temps !$"

Route110_Text_EdwinIntro:
	.string "Puis-je voir votre POKéMON ? Juste\n"
	.string "un coup d'oeil, s'il vous plaît ?$"

Route110_Text_EdwinDefeated:
	.string "Je voulais compléter ma\n"
	.string "collection…$"

Route110_Text_EdwinPostBattle:
	.string "Quand je vois un POKéMON que je ne\n"
	.string "connais pas, ma passion de\p"
	.string "collectionneur s'enflamme !$"

Route110_Text_EdwinRegister:
	.string "J’aime aussi collecter les\n"
	.string "inscriptions MATTHIEUCH CALL…$"

Route110_Text_EdwinRematchIntro:
	.string "Salut, as-tu attrapé un nouveau\n"
	.string "POKéMON ? Puis-je voir votre\p"
	.string "POKéMON ? Juste un coup d'oeil,\n"
	.string "s'il vous plaît ?$"

Route110_Text_EdwinRematchDefeated:
	.string "Ton POKéMON… je t'envie.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, j'ai hâte de m'approprier tous\n"
	.string "les POKéMON rares !$"

Route110_Text_DaleIntro:
	.string "Hé! Ne te faufile pas derrière moi\n"
	.string "comme ça !$"

Route110_Text_DaleDefeated:
	.string "J'ai perdu! Merde !$"

Route110_Text_DalePostBattle:
	.string "La pêche est une question de\n"
	.string "concentration. Vous devez vous\p"
	.string "concentrer sur le flotteur.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha ! J'irais n'importe où pour\n"
	.string "montrer mon délicieux POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, chérie, ça ne marchera pas.$"

Route110_Text_IsabelPostBattle:
	.string "Plutôt que de me battre, je devrais\n"
	.string "peut-être montrer mon POKéMON au\p"
	.string "FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Ce n'était pas proche de ce que je\n"
	.string "pouvais faire pour montrer mon\p"
	.string "POKéMON. Je vous aurai comme public\n"
	.string "captif aussi souvent que possible\p"
	.string "!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha ! Je serais heureux de\n"
	.string "montrer mon POKéMON aussi souvent\p"
	.string "que vous le souhaitez !$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, chérie, ça ne marchera pas.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Je ne pense pas que je pourrai un\n"
	.string "jour arrêter de montrer mon\p"
	.string "POKéMON. Mais j'aime aussi me\n"
	.string "battre !$"

Route110_Text_TimmyIntro:
	.string "J'ai trouvé des POKéMON sympas dans\n"
	.string "l'herbe par ici !$"

Route110_Text_TimmyDefeated:
	.string "Être cool ne suffit pas pour\n"
	.string "gagner…$"

Route110_Text_TimmyPostBattle:
	.string "Il est difficile de se battre avec\n"
	.string "un POKéMON que vous venez\p"
	.string "d'attraper.$"

Route110_Text_AlyssaIntro:
	.string "Je suis tombé en CYCLING ROAD… Je\n"
	.string "vais surmonter mon embarras en me\p"
	.string "battant avec toi !$"

Route110_Text_AlyssaDefeated:
	.string "Oops! J'ai fini par perdre !$"

Route110_Text_AlyssaPostBattle:
	.string "Tomber… Perdre… C'est tellement\n"
	.string "humiliant pour moi !$"

Route110_Text_JosephIntro:
	.string "D'accord! Temps plein ! Si vous ne\n"
	.string "parvenez pas à groover, vous êtes\p"
	.string "laissé pour compte !$"

Route110_Text_JosephDefeated:
	.string "Vous êtes bien entré dans le\n"
	.string "rythme…$"

Route110_Text_JosephPostBattle:
	.string "Cela ne va pas me déprimer ! Perdre\n"
	.string "a fait de moi un homme meilleur !$"

Route110_Text_KalebIntro:
	.string "Quand de mignons POKéMON\n"
	.string "s'entraident... Vous ne verrez pas\p"
	.string "de spectacle plus adorable !$"

Route110_Text_KalebDefeated:
	.string "N'avez-vous ni compassion ni pitié\n"
	.string "?$"

Route110_Text_KalebPostBattle:
	.string "D'accord, d'accord, vous avez fait\n"
	.string "de votre mieux, mes jolies.$"

Route111_Text_DrewIntro:
	.string "Oh hey! Ces GO-GOGGLES vous\n"
	.string "conviennent. Mais je pense qu'ils\p"
	.string "me vont mieux. Décidons à qui ils\n"
	.string "ressemblent le plus dans une\p"
	.string "bataille !$"

Route111_Text_DrewDefeat:
	.string "Je ne pouvais pas voir ce qui se\n"
	.string "passait à mes côtés à cause des\p"
	.string "GO-GOGGLES.$"

Route111_Text_DrewPostBattle:
	.string "Les GO-GOGGLES permettent de\n"
	.string "traverser les tempêtes de sable.\p"
	.string "Cela me rend heureux !$"

Route111_Text_HeidiIntro:
	.string "Je fais un pique-nique dans le\n"
	.string "désert. Vous pouvez toujours\p"
	.string "trouver un DRESSEUR, pour que je\n"
	.string "puisse aussi profiter d'une\p"
	.string "bataille ici !$"

Route111_Text_HeidiDefeat:
	.string "Ohhh ! Tu es méchant !$"

Route111_Text_HeidiPostBattle:
	.string "Lorsque vous combattez dans une\n"
	.string "tempête de sable, faites attention\p"
	.string "aux PV de votre POKéMON. Il peut\n"
	.string "s'évanouir si vous ne le surveillez\p"
	.string "pas !$"

Route111_Text_BeauIntro:
	.string "En portant ces GO-GOGGLES, je me\n"
	.string "sens comme un super-héros. Pour le\p"
	.string "moment, personne ne peut me battre\n"
	.string "!$"

Route111_Text_BeauDefeat:
	.string "Je ne peux pas gagner uniquement\n"
	.string "grâce à l'esprit…$"

Route111_Text_BeauPostBattle:
	.string "Je serai un vrai héros un jour. Je\n"
	.string "vais travailler plus dur pour\p"
	.string "rendre mon POKéMON et moi plus\n"
	.string "forts.$"

Route111_Text_BeckyIntro:
	.string "J'ai entendu dire qu'il y avait des\n"
	.string "fossiles dans le désert. Où\p"
	.string "pourraient-ils être ?$"

Route111_Text_BeckyDefeat:
	.string "J'ai échoué…$"

Route111_Text_BeckyPostBattle:
	.string "S'ils peuvent trouver des fossiles\n"
	.string "dans le désert, cela devait être\p"
	.string "une mer auparavant.$"

Route111_Text_DustyIntro:
	.string "Cela fait trente ans que je cherche\n"
	.string "des ruines antiques ! Je dois être\p"
	.string "mis au défi ?$"

Route111_Text_DustyDefeat:
	.string "Pendant que j'ai cherché des\n"
	.string "ruines, je n'ai pas cherché de\p"
	.string "POKéMON fort.$"

Route111_Text_DustyPostBattle:
	.string "Cela fait trente ans que je cherche\n"
	.string "des ruines antiques ! Non,\p"
	.string "attendez, c'était quarante ans ?\n"
	.string "C'était quoi maintenant ?$"

Route111_Text_DustyRegister:
	.string "Je n'ai pas recherché de POKéMON\n"
	.string "difficile. Mais, pour une raison\p"
	.string "quelconque, j'aime bien POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "Cela fait trente ans que je cherche\n"
	.string "des ruines antiques ! Non,\p"
	.string "attendez, c'était quarante ans ?\n"
	.string "Quoi qu'il en soit, dois-je être\p"
	.string "mis au défi ?$"

Route111_Text_DustyRematchDefeat:
	.string "Je n'ai trouvé aucune ruine, ni\n"
	.string "aucun POKéMON fort…$"

Route111_Text_DustyPostRematch:
	.string "Cela fait trente ans que je cherche\n"
	.string "des ruines antiques ! Non, attends,\p"
	.string "est-ce que ça fait quarante ans que\n"
	.string "je cherche ? Hmm… Cela pourrait\p"
	.string "même être cinquante… Depuis combien\n"
	.string "de temps suis-je là ?$"

Route111_Text_TravisIntro:
	.string "Je suis pleine de peps ! Et mon\n"
	.string "POKéMON est plein d'entrain aussi\p"
	.string "!$"

Route111_Text_TravisDefeat:
	.string "Mon POKéMON a perdu du peps…$"

Route111_Text_TravisPostBattle:
	.string "Quand je vois un DRESSEUR avec\n"
	.string "beaucoup de peps, je ne peux\p"
	.string "m'empêcher de regarder.$"

Route111_Text_IreneIntro:
	.string "Je ne sais pas où tu vas, mais\n"
	.string "aimerais-tu te battre ?$"

Route111_Text_IreneDefeat:
	.string "Oh, tu es terriblement bon !$"

Route111_Text_IrenePostBattle:
	.string "Je pense que je devrais aller à\n"
	.string "MONT CHIMNEE, mais la vue par ici\p"
	.string "est également très belle.$"

Route111_Text_DaisukeIntro:
	.string "Pour m'entraîner, je défie tous\n"
	.string "ceux que je rencontre !$"

Route111_Text_DaisukeDefeat:
	.string "Oncle! J'abandonne !$"

Route111_Text_DaisukePostBattle:
	.string "Tout ce que je peux faire, c'est\n"
	.string "continuer à m'entraîner jusqu'à ce\p"
	.string "que je puisse vaincre des DRESSEURS\n"
	.string "forts comme vous.$"

Route111_Text_WiltonIntro:
	.string "Montre-moi à quel point tu as\n"
	.string "endurci ton POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Je vois, vous les avez\n"
	.string "considérablement durcis.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON et les dresseurs apprennent\n"
	.string "beaucoup en combattant. Ce qui est\p"
	.string "important c'est de ne jamais\n"
	.string "abandonner même si vous perdez.$"

Route111_Text_WiltonRegister:
	.string "Il y a beaucoup à apprendre de\n"
	.string "votre style de formation. Je\p"
	.string "demande une revanche si cela vous\n"
	.string "convient.$"

Route111_Text_WiltonRematchIntro:
	.string "Nous nous entraînons ici pour\n"
	.string "élever notre jeu au niveau\p"
	.string "supérieur. Restez et entraînez-vous\n"
	.string "avec nous !$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, tu es décent !$"

Route111_Text_WiltonPostRematch:
	.string "Puisque vous êtes si fort, vous\n"
	.string "devriez viser la LIGUE POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Oh, vos POKéMON ressemblent à des\n"
	.string "acteurs sérieux. Je dois te\p"
	.string "demander des fiançailles.$"

Route111_Text_BrookeDefeat:
	.string "Ils n'ont pas seulement l'air\n"
	.string "forts, ils sont forts !$"

Route111_Text_BrookePostBattle:
	.string "Je pensais augmenter mon POKéMON\n"
	.string "avec diligence, mais, oh non, il\p"
	.string "reste encore beaucoup à faire.$"

Route111_Text_BrookeRegister:
	.string "J'aimerais pouvoir devenir ami avec\n"
	.string "des personnes plus fortes comme toi\p"
	.string "!$"

Route111_Text_BrookeRematchIntro:
	.string "Vous pouvez rendre POKéMON plus\n"
	.string "fort ou plus faible selon les\p"
	.string "mouvements que vous leur apprenez.\n"
	.string "Quels types de mouvements votre\p"
	.string "POKéMON connaît-il ?$"

Route111_Text_BrookeRematchDefeat:
	.string "Vous leur avez appris de bons\n"
	.string "mouvements !$"

Route111_Text_BrookePostRematch:
	.string "J'aurais peut-être dû empêcher mon\n"
	.string "POKéMON d'évoluer jusqu'à ce qu'il\p"
	.string "apprenne de meilleurs mouvements…$"

Route111_Text_CeliaIntro:
	.string "Je n'aurais pas dû venir dans un\n"
	.string "endroit comme celui-ci pour un\p"
	.string "pique-nique !$"

Route111_Text_CeliaDefeat:
	.string "Waouh ! Je n'aurais vraiment pas dû\n"
	.string "venir !$"

Route111_Text_CeliaPostBattle:
	.string "Dans une tempête de sable comme\n"
	.string "celle-ci, je ne peux pas définir\p"
	.string "les endroits pour un pique-nique\n"
	.string "même avec mes GO-GOGGLES sur…$"

Route111_Text_BryanIntro:
	.string "À quel point es-tu dur ? Nous\n"
	.string "allons révéler ce secret !$"

Route111_Text_BryanDefeat:
	.string "Oh! Ta force! C’est entouré de\n"
	.string "mystère !$"

Route111_Text_BryanPostBattle:
	.string "Ce désert recèle des mystères dans\n"
	.string "ses sables mouvants !$"

Route111_Text_BrandenIntro:
	.string "Je te donnerai un peu de mon\n"
	.string "sandwich si tu perds.$"

Route111_Text_BrandenDefeat:
	.string "Tch ! Je pensais qu'un sandwich\n"
	.string "suffirait comme pot-de-vin…$"

Route111_Text_BrandenPostBattle:
	.string "Mon SANDSHREW adore manger mes\n"
	.string "sandwichs.$"

Route111_Text_TyronIntro:
	.string "C'est mon type de POKéMON préféré\n"
	.string "!$"

Route111_Text_TyronDefeat:
	.string "Attendez! Avez-vous bien regardé\n"
	.string "mon POKéMON ?$"

Route111_Text_TyronPostBattle:
	.string "Lors d'une bataille, j'aime montrer\n"
	.string "mon POKéMON. Je parie que tout le\p"
	.string "monde ressent cela lorsqu'il entre\n"
	.string "dans une bataille !$"

Route111_Text_CelinaIntro:
	.string "Montre-moi comment mettre un peu\n"
	.string "d'excitation dans ma vie.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Mon Dieu… C'était trop\n"
	.string "d'excitation.$"

Route111_Text_CelinaPostBattle:
	.string "Mon pouls continue de s'accélérer.\n"
	.string "Vous êtes un fabuleux\p"
	.string "DRESSEUR.$"

Route111_Text_HaydenIntro:
	.string "Quand on est aussi affamé que moi,\n"
	.string "il n'y a pas de place pour la pitié\p"
	.string "!$"

Route111_Text_HaydenDefeat:
	.string "Gémir…$"

Route111_Text_HaydenPostBattle:
	.string "Mon estomac gargouille ! Peut-être\n"
	.string "que je peux griller des BAIES…$"

Route111_Text_BiancaIntro:
	.string "Vous venez de MAUVILLE ? Alors vous\n"
	.string "devriez être plein d'énergie !$"

Route111_Text_BiancaDefeat:
	.string "Oh la la! C'est beaucoup à prendre\n"
	.string "!$"

Route111_Text_BiancaPostBattle:
	.string "Cette route ici… Vous avez tout un\n"
	.string "chemin à parcourir.$"

Route112_Text_BriceIntro:
	.string "Hahahaha ! Et si on se battait ?\n"
	.string "Toi et moi! Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "J'ai perdu! Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha ! Quelque chose m'est\n"
	.string "monté dans le nez !\p"
	.string "Hahahaha-hatchoo !$"

Route112_Text_TrentIntro:
	.string "Mes jambes sont solides à force de\n"
	.string "monter et descendre les montagnes.\p"
	.string "Ils ne vont pas se boucler\n"
	.string "facilement, mon ami !$"

Route112_Text_TrentDefeat:
	.string "Aie! J'avais des crampes dans les\n"
	.string "jambes !$"

Route112_Text_TrentPostBattle:
	.string "Essayez la randonnée, et je veux\n"
	.string "dire vraiment, sur ces sentiers de\p"
	.string "montagne avec un sac lourd pesant\n"
	.string "des dizaines de livres. Cela, mon\p"
	.string "ami, mettra votre corps en pleine\n"
	.string "forme.$"

Route112_Text_TrentRegister:
	.string "Aïe, j'ai des crampes dans les\n"
	.string "jambes. Peux-tu me sortir des\p"
	.string "bandages de mon sac à dos ? Non,\n"
	.string "c'est mon POKéNAV ! Oh, très bien,\p"
	.string "je vais t'inscrire.$"

Route112_Text_TrentRematchIntro:
	.string "Je suis resté en forme grâce à la\n"
	.string "randonnée. Le pouvoir, j'en ai à la\p"
	.string "pelle !$"

Route112_Text_TrentRematchDefeat:
	.string "J'ai été trompé au pouvoir ?$"

Route112_Text_TrentRematchPostBattle:
	.string "J'ai entendu dire qu'il y avait des\n"
	.string "DRESSEURS très coriaces en\p"
	.string "plus de MONT CHIMNEE. J'ai\n"
	.string "l'intention de monter là-haut et de\p"
	.string "leur lancer un défi !$"

Route112_Text_LarryIntro:
	.string "Je suis fort. Je ne pleurerai pas\n"
	.string "si je perds.$"

Route112_Text_LarryDefeat:
	.string "Waouh !$"

Route112_Text_LarryPostBattle:
	.string "Je ne pleure pas parce que ma maman\n"
	.string "me manque ! pleurnicheur…$"

Route112_Text_CarolIntro:
	.string "Quand on pique-nique, eh bien, il\n"
	.string "suffit de chanter ! Allez, chante\p"
	.string "avec moi !$"

Route112_Text_CarolDefeat:
	.string "Oh, tu es si fort !$"

Route112_Text_CarolPostBattle:
	.string "Peu importe que vous soyez bon ou\n"
	.string "mauvais en chant ou en POKéMON. Si\p"
	.string "vous vous amusez le plus, vous\n"
	.string "gagnez !$"

Route112_Text_BryantIntro:
	.string "J'ai attrapé un POKéMON brûlant\n"
	.string "dans CHEMIN ARDENT ! Jetez un\p"
	.string "oeil!$"

Route112_Text_BryantDefeat:
	.string "Quelle aventure cahoteuse !$"

Route112_Text_BryantPostBattle:
	.string "J'aime la façon dont tu te bats. Il\n"
	.string "y a un certain flair.$"

Route112_Text_ShaylaIntro:
	.string "Oh, n'es-tu pas un adorable\n"
	.string "DRESSEUR ! S'il vous plaît, j'ai\p"
	.string "besoin d'une bataille romantique !\n"
	.string "Je suis plutôt décent !$"

Route112_Text_ShaylaDefeat:
	.string "Oh, comme tu es fort ! Vous m'avez\n"
	.string "fait un sacré choc !$"

Route112_Text_ShaylaPostBattle:
	.string "Êtes-vous occupé en ce moment? Je\n"
	.string "pensais que peut-être nous\p"
	.string "pourrions avoir une revanche\n"
	.string "maintenant… Mais ce n'est pas grave\p"
	.string "si vous êtes occupé.$"

Route113_Text_JaylenIntro:
	.string "Pouvez-vous deviner pourquoi c'est\n"
	.string "si cool ici ?$"

Route113_Text_JaylenDefeat:
	.string "Piuuuuh ! Ça pue !$"

Route113_Text_JaylenPostBattle:
	.string "Les cendres volcaniques bloquent le\n"
	.string "soleil et ne font donc pas très\p"
	.string "chaud. C'est bon pour moi, je ne\n"
	.string "supporte pas la chaleur !$"

Route113_Text_DillonIntro:
	.string "L'éruption du volcan est la preuve\n"
	.string "que la terre est vivante.$"

Route113_Text_DillonDefeat:
	.string "Tu es une sorte de fort !$"

Route113_Text_DillonPostBattle:
	.string "Aie! Owww! Je ne vois pas ! J'ai de\n"
	.string "la cendre dans mes cils !\p"
	.string "L'obtenir? Des cendres et des cils\n"
	.string "? D'accord, c'était mauvais,\p"
	.string "désolé…$"

Route113_Text_MadelineIntro:
	.string "J'utilise ce parasol pour éloigner\n"
	.string "ces cendres volcaniques sales et\p"
	.string "dégueulasses de mon cher NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Huff,huff… je suis épuisé…$"

Route113_Text_MadelinePostBattle:
	.string "Tu es très doué pour ça. Je dois\n"
	.string "dire que je suis impressionné!$"

Route113_Text_MadelineRegister:
	.string "Tiens, glisse-toi sous mon parasol.\n"
	.string "Laissez-moi vous inscrire dans mon\p"
	.string "POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, bonjour, ça ne fait pas\n"
	.string "longtemps ? Puis-je vous inviter à\p"
	.string "combattre ?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, comme c'est super !$"

Route113_Text_MadelinePostRematch:
	.string "Vous êtes resté très bon dans ce\n"
	.string "domaine. Je dois dire que je suis\p"
	.string "impressionné!$"

Route113_Text_LaoIntro:
	.string "De mes cendres je sursaute ! Salut\n"
	.string "! Je te défie !$"

Route113_Text_LaoDefeat:
	.string "Avec honneur, j'admets ma défaite\n"
	.string "!$"

Route113_Text_LaoPostBattle:
	.string "Je dois perfectionner l'art de la\n"
	.string "dissimulation. Je te dis adieu.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah ! Soyez témoin de\n"
	.string "l'ancienne technique ninja de\p"
	.string "l'enregistrement POKéNAV !$"

Route113_Text_LaoRematchIntro:
	.string "De mes cendres je sursaute ! Salut\n"
	.string "! Je te défie !$"

Route113_Text_LaoRematchDefeat:
	.string "Avec honneur, j'admets ma défaite\n"
	.string "!$"

Route113_Text_LaoPostRematch:
	.string "Ma dissimulation parfaite a été\n"
	.string "déçue par mes compétences de combat\p"
	.string "immatures… Je te dis adieu.$"

Route113_Text_LungIntro:
	.string "Merci de m'avoir trouvé ! Mais il\n"
	.string "faut encore se battre !$"

Route113_Text_LungDefeat:
	.string "Je vais utiliser mon ninjutsu sur\n"
	.string "toi… “ MANTEAU TOURBILLON DE\p"
	.string "CENDRES VOLCANIQUES ” ! …Quoi?\n"
	.string "C'est déjà fini ?$"

Route113_Text_LungPostBattle:
	.string "Tu sais ce qu'il y a de minable à\n"
	.string "se cacher ? On se sent seul si\p"
	.string "personne ne vient.$"

Route113_Text_ToriIntro:
	.string "TORI : Nous deux, nous collectons\n"
	.string "les cendres. Nous combattons\p"
	.string "également POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI : Nous avons perdu… C'est\n"
	.string "ennuyeux, alors je vais récupérer\p"
	.string "encore quelques cendres.$"

Route113_Text_ToriPostBattle:
	.string "TORI : Combien de cendres\n"
	.string "avons-nous ? Assez pour une FLÛTE\p"
	.string "BLANCHE, j'espère.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI : Nous voulons nous battre en\n"
	.string "2 contre 2. Si nous ne le faisions\p"
	.string "pas, nous perdrions !$"

Route113_Text_TiaIntro:
	.string "TIA : Nous récupérons tous les deux\n"
	.string "les cendres. Nous combattons\p"
	.string "également POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA : On ne pouvait pas gagner…\n"
	.string "C'est ennuyeux, alors je récupère\p"
	.string "encore quelques cendres.$"

Route113_Text_TiaPostBattle:
	.string "TIA : Nous avons beaucoup de\n"
	.string "cendres ! Je pense que c'est\p"
	.string "suffisant pour une FLÛTE BLANCHE !$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA : Nous voulons nous battre en 2\n"
	.string "contre 2. Si nous ne le faisons\p"
	.string "pas, nous ne gagnerons pas !$"

Route113_Text_CobyIntro:
	.string "Pfft, avec ces ailes je peux\n"
	.string "t'éloigner !$"

Route113_Text_CobyDefeat:
	.string "Un… Quoi ?$"

Route113_Text_CobyPostBattle:
	.string "Je ne sais pas quoi dire quand je\n"
	.string "me fais battre si facilement…$"

Route113_Text_SophieIntro:
	.string "La chaleur ici me rend somnolent.\n"
	.string "Combattez avec moi pour que je\p"
	.string "puisse rester éveillé.$"

Route113_Text_SophieDefeat:
	.string "C'est un rêve. J'en suis sûr…$"

Route113_Text_SophiePostBattle:
	.string "Perdre me brûle… Je vais juste\n"
	.string "dormir ici ! Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Étiez-vous peut-être en train de\n"
	.string "collecter des cendres volcaniques\p"
	.string "?$"

Route113_Text_LawrenceDefeat:
	.string "Héhé. Nous avons été battus\n"
	.string "proprement.$"

Route113_Text_LawrencePostBattle:
	.string "Je devrais aussi me cacher sous les\n"
	.string "cendres.$"

Route113_Text_WyattIntro:
	.string "V-tu veux te battre avec moi ? Même\n"
	.string "si je viens d'attraper mon POKéMON\p"
	.string "?$"

Route113_Text_WyattDefeat:
	.string "Vous êtes tous heureux de gagner ?\n"
	.string "Même si ce n'est que moi ?$"

Route113_Text_WyattPostBattle:
	.string "Oh, alors maintenant tu veux dire\n"
	.string "un mot au perdant ? N'êtes-vous pas\p"
	.string "simplement le plus cool ? Hum!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo ! … … Vous êtes censé\n"
	.string "crier “ yodelayhihoo ” puisque ça\p"
	.string "n'a pas d'écho ici !$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "Quand j'étais tout petit, je\n"
	.string "croyais qu'il y avait quelqu'un qui\p"
	.string "me copiait et criait en retour : “\n"
	.string "Yodelayheehoo ”.$"

Route114_Text_LucasIntro:
	.string "Si vous n'êtes pas préparé, vous ne\n"
	.string "devriez pas être en montagne !$"

Route114_Text_LucasDefeat:
	.string "Les montagnes sont impitoyables…$"

Route114_Text_LucasPostBattle:
	.string "En hiver, les montagnes deviennent\n"
	.string "meurtrières avec des blizzards et\p"
	.string "des avalanches.$"

Route114_Text_ShaneIntro:
	.string "Le camping, c'est amusant ! Vous\n"
	.string "pouvez pêcher, faire griller des\p"
	.string "guimauves et raconter des histoires\n"
	.string "effrayantes ! Mais le meilleur de\p"
	.string "tous, ce sont les combats POKéMON\n"
	.string "!$"

Route114_Text_ShaneDefeat:
	.string "Beaucoup trop fort !$"

Route114_Text_ShanePostBattle:
	.string "Je trouve ça génial de pouvoir\n"
	.string "aller camper avec mon POKéMON.$"

Route114_Text_NancyIntro:
	.string "J'ai besoin de faire de l'exercice\n"
	.string "après un repas. Faisons un match !$"

Route114_Text_NancyDefeat:
	.string "Ah non !$"

Route114_Text_NancyPostBattle:
	.string "Je viens de prendre un délicieux\n"
	.string "repas. Je deviens somnolent…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu… Envie de combattre mon\n"
	.string "POKéMON ?$"

Route114_Text_SteveDefeat:
	.string "M-Mon POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un gros corps tout grumeleux et\n"
	.string "dur, des cornes énormes et des\p"
	.string "crocs vicieux… Ufufufufu… J'aurais\n"
	.string "aimé avoir un POKéMON comme ça…$"

Route114_Text_SteveRegister:
	.string "N'oublie pas ce que tu m'as fait !\n"
	.string "Je vais le faire pour que tu ne\p"
	.string "puisses pas oublier !$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu… Allez, combats mon\n"
	.string "POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Je me sens tellement chanceux de\n"
	.string "pouvoir voir ton POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu… Quand je vois POKéMON\n"
	.string "se battre, j'ai des frissons et des\p"
	.string "tremblements…$"

Route114_Text_BernieIntro:
	.string "Si vous allumez un feu de camp,\n"
	.string "assurez-vous d'avoir de l'eau à\p"
	.string "portée de main.$"

Route114_Text_BernieDefeat:
	.string "Merci d'avoir éteint mon feu !$"

Route114_Text_BerniePostBattle:
	.string "Il faut vraiment faire attention à\n"
	.string "tout type d'incendie dans une\p"
	.string "forêt. Ne sous-estimez jamais le\n"
	.string "pouvoir du feu.$"

Route114_Text_BernieRegister:
	.string "Vous avez mis le feu à mon esprit.\n"
	.string "Inscrivons-nous les uns les autres\p"
	.string "!$"

Route114_Text_BernieRematchIntro:
	.string "Avez-vous appris à garder de l'eau\n"
	.string "à portée de main pour les feux de\p"
	.string "camp ?$"

Route114_Text_BernieRematchDefeat:
	.string "J'ai été arrosé avant de pouvoir\n"
	.string "m'enflammer, je suppose.$"

Route114_Text_BerniePostRematch:
	.string "Il faut vraiment faire attention à\n"
	.string "tout type d'incendie dans une\p"
	.string "forêt. Ne sous-estimez jamais le\n"
	.string "pouvoir du feu.$"

Route114_Text_ClaudeIntro:
	.string "Si nous pêchions, tu n'aurais\n"
	.string "aucune chance contre moi. Alors,\p"
	.string "apportez votre POKéMON !$"

Route114_Text_ClaudeDefeat:
	.string "Si nous pêchions, j'aurais gagné…$"

Route114_Text_ClaudePostBattle:
	.string "Je pense que je vais tenter ma\n"
	.string "chance pour en atterrir un gros à\p"
	.string "SITE MGUIDOEORE. Il doit y avoir\n"
	.string "quelque chose là-dedans. Je le sais\p"
	.string "juste.$"

Route114_Text_NolanIntro:
	.string "J'aime pecher. Mais j'aime aussi me\n"
	.string "battre ! Si quelqu'un me défie, je\p"
	.string "suis là, même si je pêche.$"

Route114_Text_NolanDefeat:
	.string "J'aime me battre, mais cela ne veut\n"
	.string "pas dire que je suis bon dans ce\p"
	.string "domaine…$"

Route114_Text_NolanPostBattle:
	.string "Cette fois, je le ferai ! Je pense\n"
	.string "toujours ça, donc je ne peux pas\p"
	.string "m'éloigner de la pêche ou de\n"
	.string "POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA : Eh bien, bien sûr. J'en suis\n"
	.string "d'humeur. Je vais vous en apprendre\p"
	.string "un peu plus sur POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA : Quel style de combat\n"
	.string "incroyable !$"

Route114_Text_TyraPostBattle:
	.string "TYRA : J'enseignais POKéMON à mon\n"
	.string "junior IVY.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA : Riez… Si vous voulez vous\n"
	.string "battre avec nous, un seul POKéMON\p"
	.string "ne suffit pas !$"

Route114_Text_IvyIntro:
	.string "IVY : Qui vous a appris POKéMON ?$"

Route114_Text_IvyDefeat:
	.string "IVY : Quel style de combat\n"
	.string "incroyable !$"

Route114_Text_IvyPostBattle:
	.string "IVY : J'ai commencé à entraîner\n"
	.string "POKéMON parce que TYRA, mon mentor\p"
	.string "étudiant, m'a appris !$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY : Tu n'as qu'un seul POKéMON ?\n"
	.string "Je pense que ça doit se sentir\p"
	.string "seul.$"

Route114_Text_KaiIntro:
	.string "J'en ai décroché un gros ! Un\n"
	.string "énorme, je vous le dis !$"

Route114_Text_KaiDefeat:
	.string "De quoi s’agissait-il ? Le mien\n"
	.string "a-t-il perdu en taille ?$"

Route114_Text_KaiPostBattle:
	.string "D'accord! Je vais juste m'en pêcher\n"
	.string "un plus gros !$"

Route114_Text_CharlotteIntro:
	.string "Moi! Je ne suis pas seulement un\n"
	.string "joli visage !$"

Route114_Text_CharlotteDefeat:
	.string "Ce n'était pas mignon du tout !$"

Route114_Text_CharlottePostBattle:
	.string "Je ne veux pas d'un POKéMON juste\n"
	.string "mignon. J'adore les mignons qui ont\p"
	.string "une bizarrerie ou deux !$"

Route114_Text_AngelinaIntro:
	.string "Avez-vous beaucoup fait évoluer\n"
	.string "votre POKéMON ?$"

Route114_Text_AngelinaDefeat:
	.string "Oh je vois. C'est bon à savoir.$"

Route114_Text_AngelinaPostBattle:
	.string "Certains POKéMON changent tellement\n"
	.string "lorsqu'ils évoluent, c'est\p"
	.string "surprenant !$"

Route115_Text_TimothyIntro:
	.string "Hm… Tu as l'air plutôt capable…\n"
	.string "Laisse-moi te tenir compagnie !$"

Route115_Text_TimothyDefeat:
	.string "Tu es bien plus fort que je ne\n"
	.string "l'avais imaginé !$"

Route115_Text_TimothyPostBattle:
	.string "Il n’existe pas de génie né. Tout\n"
	.string "dépend de l'effort ! C'est ce que\p"
	.string "je crois…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Une perte aussi complète n’est\n"
	.string "plus qu’un lointain souvenir. Si\p"
	.string "vous le permettez, je souhaite\n"
	.string "avoir une autre occasion de\p"
	.string "combattre.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Comme toujours, votre agilité\n"
	.string "parle d'elle-même. Viens, tiens-moi\p"
	.string "compagnie !$"

Route115_Text_TimothyRematchDefeat:
	.string "Toujours aussi fort !$"

Route115_Text_TimothyPostRematch:
	.string "Tout ce qu'il faut, c'est des\n"
	.string "efforts ! J'ai perdu parce que je\p"
	.string "n'ai pas fait assez d'efforts !$"

Route115_Text_KoichiIntro:
	.string "Toi! Mon MACHOP! Exigez une\n"
	.string "bataille !$"

Route115_Text_KoichiDefeat:
	.string "Aïe, aïe, aïe !$"

Route115_Text_KoichiPostBattle:
	.string "Mon équipage MACHOP ! Tant qu’ils\n"
	.string "chercheront le pouvoir, je\p"
	.string "deviendrai fort avec eux !$"

Route115_Text_NobIntro:
	.string "Ma plus grande compétence est de\n"
	.string "casser des briques avec mon front\p"
	.string "!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah ! J'ai la tête cassée !$"

Route115_Text_NobPostBattle:
	.string "J'enseigne le karaté à mon POKéMON.\n"
	.string "On dirait qu'ils deviendront bien\p"
	.string "meilleurs que moi. Je suis excité à\n"
	.string "ce sujet.$"

Route115_Text_NobRegister:
	.string "Tu m'impressionnes! Donnez-moi une\n"
	.string "revanche après avoir refait mon\p"
	.string "entraînement !$"

Route115_Text_NobRematchIntro:
	.string "Après que tu m'as battu, nous nous\n"
	.string "sommes entraînés dur pour améliorer\p"
	.string "nos compétences. Allez, donne-nous\n"
	.string "une revanche !$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah ! Nous avons encore perdu\n"
	.string "!$"

Route115_Text_NobPostRematch:
	.string "Mon POKéMON deviendra plus fort !\n"
	.string "Je vais redoubler d'entraînement !$"

Route115_Text_CyndyIntro:
	.string "Cette plage est mon lieu\n"
	.string "d'entraînement secret !\p"
	.string "N'intervenez pas !$"

Route115_Text_CyndyDefeat:
	.string "Je ne me suis pas assez entraîné !$"

Route115_Text_CyndyPostBattle:
	.string "Le sable agit comme un coussin pour\n"
	.string "réduire l’impact et prévenir les\p"
	.string "blessures. C'est l'endroit idéal\n"
	.string "pour s'entraîner.$"

Route115_Text_CyndyRegister:
	.string "D'accord, très bien, tu es libre de\n"
	.string "venir ici. En retour, j'aimerais\p"
	.string "vous combattre à nouveau.$"

Route115_Text_CyndyRematchIntro:
	.string "D'accord, commençons cette bataille\n"
	.string "!$"

Route115_Text_CyndyRematchDefeat:
	.string "Je peux me battre mais mon\n"
	.string "POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Même quand je perds, j’en profite\n"
	.string "toujours. C'est sûrement parce que\p"
	.string "j'adore POKéMON.$"

Route115_Text_HectorIntro:
	.string "J'ai un POKéMON rare ! Voudrais-tu\n"
	.string "que je te montre ?$"

Route115_Text_HectorDefeat:
	.string "Vous… Vous voulez mon POKéMON,\n"
	.string "n'est-ce pas ?$"

Route115_Text_HectorPostBattle:
	.string "J'ai ce POKéMON rare. C'est\n"
	.string "suffisant pour me satisfaire.$"

Route115_Text_KyraIntro:
	.string "Je me battrai pendant que je cours\n"
	.string "! Essayez de me suivre !$"

Route115_Text_KyraDefeat:
	.string "Halètement, halètement…$"

Route115_Text_KyraPostBattle:
	.string "J'ai fait l'erreur d'essayer de me\n"
	.string "battre en courant ! Je devrais\p"
	.string "courir pour me calmer…$"

Route115_Text_JaidenIntro:
	.string "Prend ça! Attaque ninja Ultra\n"
	.string "POKéMON !$"

Route115_Text_JaidenDefeat:
	.string "Waaah ! Notre stratégie a échoué !$"

Route115_Text_JaidenPostBattle:
	.string "Mais mes POKéMON étaient ultra,\n"
	.string "n'est-ce pas ?$"

Route115_Text_HeleneIntro:
	.string "Mes POKéMON ont une force de niveau\n"
	.string "ceinture noire !$"

Route115_Text_HeleneDefeat:
	.string "C'est trop humiliant !$"

Route115_Text_HelenePostBattle:
	.string "Je rencontre rarement quelqu'un qui\n"
	.string "est meilleur que moi… je comprends\p"
	.string "maintenant ! Vous êtes un GYM\n"
	.string "LEADER, n'est-ce pas ?$"

Route115_Text_AlixIntro:
	.string "Nos regards se sont croisés ! Il\n"
	.string "n'y a plus moyen de s'en sortir\p"
	.string "maintenant !$"

Route115_Text_AlixDefeat:
	.string "Waouh ! Pas mal !$"

Route115_Text_AlixPostBattle:
	.string "Tant pis. Je pense que je vais\n"
	.string "TÉLÉPORTER chez moi.$"

Route115_Text_MarleneIntro:
	.string "Vous avez perturbé ma méditation…\n"
	.string "Vous en serez puni.$"

Route115_Text_MarleneDefeat:
	.string "Vous avez brisé ma concentration !$"

Route115_Text_MarlenePostBattle:
	.string "Je méditais avec mon POKéMON. Mais\n"
	.string "cet endroit n'est pas très\p"
	.string "paisible…$"

Route116_Text_ClarkIntro:
	.string "Si le tunnel ne passe pas, je\n"
	.string "passerai par-dessus.$"

Route116_Text_ClarkDefeat:
	.string "Halètement… Halètement… Perdre m'a\n"
	.string "fatigué…$"

Route116_Text_ClarkPostBattle:
	.string "Ce n'est pas grave s'il n'y a pas\n"
	.string "de tunnel. Pour un RANDONNEUR, les\p"
	.string "montagnes sont des routes !$"

Route116_Text_JoeyIntro:
	.string "Ma règle POKéMON ! Découvrez-les !$"

Route116_Text_JoeyDefeat:
	.string "Aie! Une égratignure ! Je dois\n"
	.string "mettre un pansement !$"

Route116_Text_JoeyPostBattle:
	.string "Les bandages sont des signes de\n"
	.string "ténacité ! J'en ai un autre !$"

Route116_Text_JoseIntro:
	.string "Mes POKéMON BUG sont coriaces !\n"
	.string "Battons-nous !$"

Route116_Text_JoseDefeat:
	.string "J'ai perdu! Je pensais que je\n"
	.string "t'avais !$"

Route116_Text_JosePostBattle:
	.string "BUG POKéMON évolue rapidement.\n"
	.string "Alors ils deviennent vite forts\p"
	.string "aussi.$"

Route116_Text_JaniceIntro:
	.string "Laissez-moi vous apprendre à quel\n"
	.string "point mon adorable POKéMON est fort\p"
	.string "!$"

Route116_Text_JaniceDefeat:
	.string "Tu es un cran au-dessus de moi…$"

Route116_Text_JanicePostBattle:
	.string "Des POKéMON qui possèdent de la\n"
	.string "gentillesse et de la puissance,\p"
	.string "c'est l'idéal, je pense.$"

Route116_Text_JerryIntro:
	.string "À l'ÉCOLE DES DRESSEURS, on\n"
	.string "apprend toutes sortes de choses. Je\p"
	.string "veux tester les choses en vrai !$"

Route116_Text_JerryDefeat:
	.string "Je me suis relâché à l'école… C'est\n"
	.string "pour ça que j'ai perdu.$"

Route116_Text_JerryPostBattle:
	.string "Je vais devoir refaire quelques\n"
	.string "cours à l'ÉCOLE DES\p"
	.string "DRESSEURS. Si je ne le fais\n"
	.string "pas, ROXANNE sera cuite à la\p"
	.string "vapeur.$"

Route116_Text_JerryRegister1:
	.string "J'ai appris à l'ÉCOLE DES DRESSEURS\n"
	.string "qu'un POKéNAV peut enregistrer des\p"
	.string "DRESSEURS. Je ne comprends pas\n"
	.string "vraiment ce que cela signifie,\p"
	.string "alors puis-je simplement essayer ?$"

Route116_Text_JerryRegister2:
	.string "J'ai appris à l'ÉCOLE DES DRESSEURS\n"
	.string "qu'un POKéNAV peut enregistrer des\p"
	.string "DRESSEURS. Je ne comprends pas\n"
	.string "vraiment ce que cela signifie,\p"
	.string "alors puis-je simplement essayer ?$"

Route116_Text_JerryRematchIntro:
	.string "J'ai étudié sérieusement à l'ÉCOLE\n"
	.string "DES DRESSEURS. Je ne perdrai\p"
	.string "pas comme la dernière fois.$"

Route116_Text_JerryRematchDefeat:
	.string "Hein ? J'ai étudié assidûment.$"

Route116_Text_JerryPostRematch:
	.string "Je vais devoir refaire quelques\n"
	.string "cours à l'ÉCOLE DES\p"
	.string "DRESSEURS. Si je ne le fais\n"
	.string "pas, ROXANNE sera cuite à la\p"
	.string "vapeur.$"

Route116_Text_KarenIntro:
	.string "J'étudie à l'école et j'étudie\n"
	.string "aussi sur le chemin du retour !$"

Route116_Text_KarenDefeat:
	.string "Je suis sous le choc : j'ai perdu\n"
	.string "?$"

Route116_Text_KarenPostBattle:
	.string "Awww, je ne deviendrai jamais une\n"
	.string "DRESSEUR élégante comme\p"
	.string "ROXANNE de cette façon !$"

Route116_Text_KarenRegister1:
	.string "Oh wow! C'est pas un POKéNAV ? J'en\n"
	.string "ai un aussi! S'il vous plaît,\p"
	.string "inscrivez-moi !$"

Route116_Text_KarenRegister2:
	.string "Oh wow! C'est pas un POKéNAV ? J'en\n"
	.string "ai un aussi! S'il vous plaît,\p"
	.string "inscrivez-moi !$"

Route116_Text_KarenRematchIntro:
	.string "J'ai beaucoup étudié depuis que je\n"
	.string "t'ai vu. Vous devez voir mes\p"
	.string "réalisations !$"

Route116_Text_KarenRematchDefeat:
	.string "Je suis en état de choc. J'ai\n"
	.string "encore perdu ?$"

Route116_Text_KarenPostRematch:
	.string "Vous avez battu ROXANNE ? Je ne\n"
	.string "peux pas te battre, alors. Pas\p"
	.string "encore.$"

Route116_Text_SarahIntro:
	.string "Juste pour que vous le sachiez, je\n"
	.string "n'ai jamais été battu par qui que\p"
	.string "ce soit.$"

Route116_Text_SarahDefeat:
	.string "Oh mon Dieu. C'est une nouvelle\n"
	.string "expérience pour moi.$"

Route116_Text_SarahPostBattle:
	.string "Ma vie de luxe m'offre tout ce que\n"
	.string "je peux désirer. Cependant,\p"
	.string "lorsqu'il s'agit de POKéMON, ma\n"
	.string "richesse n'a aucun sens.$"

Route116_Text_DawsonIntro:
	.string "Lorsque vous poserez vos yeux sur\n"
	.string "la magnifique fourrure de mon\p"
	.string "POKéMON, leur beauté vous rendra\n"
	.string "impuissant !$"

Route116_Text_DawsonDefeat:
	.string "Oh, bébé, dis que ce n'est pas le\n"
	.string "cas !$"

Route116_Text_DawsonPostBattle:
	.string "Oh non, non, non ! Vous avez\n"
	.string "ébouriffé la fourrure de mon\p"
	.string "POKéMON ! Tu as aussi gâché ma\n"
	.string "coiffure ! Je vais devoir appeler\p"
	.string "mon styliste maintenant !$"

Route116_Text_DevanIntro:
	.string "On va vous bercer fort !$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi! Pas de concours du tout !$"

Route116_Text_DevanPostBattle:
	.string "Je devrais essayer différents types\n"
	.string "de POKéMON, c'est ce que je devrais\p"
	.string "faire.$"

Route116_Text_JohnsonIntro:
	.string "C'est une impasse ici. Je m'ennuie,\n"
	.string "alors pouvons-nous nous battre ?$"

Route116_Text_JohnsonDefeat:
	.string "C'était amusant même si j'ai\n"
	.string "perdu.$"

Route116_Text_JohnsonPostBattle:
	.string "Tu veux rester ici et me tenir\n"
	.string "compagnie ?$"

Route117_Text_IsaacIntro:
	.string "Écoute, puis-je te demander de\n"
	.string "combattre le POKéMON que j'élève ?$"

Route117_Text_IsaacDefeat:
	.string "Vous avez superbement élevé le\n"
	.string "vôtre…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON n'est pas qu'une question\n"
	.string "de pouvoir. Polir un aspect unique\p"
	.string "de son personnage est une autre\n"
	.string "façon de profiter de POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Je vais redoubler d'entraînement.\n"
	.string "Voudriez-vous venir nous voir ?$"

Route117_Text_IsaacRematchIntro:
	.string "Les POKéMON que j'ai élevés ont\n"
	.string "l'air bien, comme avant.$"

Route117_Text_IsaacRematchDefeat:
	.string "Vous savez les élever correctement.\n"
	.string "Vous pourriez avoir des compétences\p"
	.string "en GARDE DE JOUR…$"

Route117_Text_IsaacPostRematch:
	.string "Vos POKéMON grandissent bien ! Vous\n"
	.string "devriez les inscrire aux CONCOURS.$"

Route117_Text_LydiaIntro:
	.string "S'il vous plaît, permettez-moi\n"
	.string "d'évaluer si vous avez correctement\p"
	.string "élevé votre POKéMON.$"

Route117_Text_LydiaDefeat:
	.string "Oui, ils grandissent correctement.$"

Route117_Text_LydiaPostBattle:
	.string "Essayez d'élever des POKéMON en\n"
	.string "accordant plus d'attention à leurs\p"
	.string "traits de caractère.$"

Route117_Text_LydiaRegister:
	.string "Je suis contente d'avoir rencontré\n"
	.string "en toi un superbe DRESSEUR.\p"
	.string "J'espère vous revoir.$"

Route117_Text_LydiaRematchIntro:
	.string "Permettez-moi de réévaluer si vous\n"
	.string "avez correctement élevé votre\p"
	.string "POKéMON.$"

Route117_Text_LydiaRematchDefeat:
	.string "Ils grandissent admirablement.$"

Route117_Text_LydiaPostRematch:
	.string "Les POKéMON semblent aimer\n"
	.string "différents types de {POKEBLOCK}, selon\p"
	.string "leur nature.$"

Route117_Text_DylanIntro:
	.string "Je suis en plein triathlon, mais\n"
	.string "peu importe, battons-nous !$"

Route117_Text_DylanDefeat:
	.string "Je n'ai plus d'énergie !$"

Route117_Text_DylanPostBattle:
	.string "J'ai peut-être tout gâché… J'aurais\n"
	.string "peut-être chuté pour durer pendant\p"
	.string "cette bataille…$"

Route117_Text_DylanRegister:
	.string "POKéMON doit aussi être fort ?\n"
	.string "J'aimerais que tu m'entraînes !$"

Route117_Text_DylanRematchIntro:
	.string "Je suis en plein milieu d'un\n"
	.string "triathlon, mais je suis\p"
	.string "confortablement en avance. Faisons\n"
	.string "en sorte que ce soit une bataille\p"
	.string "rapide !$"

Route117_Text_DylanRematchDefeat:
	.string "J'ai encore manqué d'énergie !$"

Route117_Text_DylanPostRematch:
	.string "J'étais au top en natation et en\n"
	.string "cyclisme, mais je ne suis pas\p"
	.string "encore très confiant avec POKéMON.$"

Route117_Text_MariaIntro:
	.string "Je fais mon entraînement de\n"
	.string "triathlon avec POKéMON, donc je\p"
	.string "suis assez confiant quant à ma\n"
	.string "vitesse.$"

Route117_Text_MariaDefeat:
	.string "Je dois m'entraîner davantage, je\n"
	.string "suppose.$"

Route117_Text_MariaPostBattle:
	.string "La formation n’a de sens que si\n"
	.string "vous la suivez régulièrement.\p"
	.string "D'accord! Je reprends mon\n"
	.string "entraînement ! Demain !$"

Route117_Text_MariaRegister:
	.string "Vous semblez vous entraîner\n"
	.string "correctement… Si vous le souhaitez,\p"
	.string "je vous affronterai plus tard !$"

Route117_Text_MariaRematchIntro:
	.string "Est-ce que vous suivez votre\n"
	.string "formation ? Bien sûr ! Laissez-moi\p"
	.string "vous montrer la preuve !$"

Route117_Text_MariaRematchDefeat:
	.string "Je dois m'entraîner davantage, je\n"
	.string "suppose.$"

Route117_Text_MariaPostRematch:
	.string "Je reprendrai l'entraînement\n"
	.string "demain. Battons-nous à nouveau un\p"
	.string "jour !$"

Route117_Text_DerekIntro:
	.string "Une fois un BUG CATCHER ! Et\n"
	.string "maintenant un BUG MANIAC ! Mais mon\p"
	.string "amour pour POKéMON reste inchangé\n"
	.string "!$"

Route117_Text_DerekDefeat:
	.string "Mon incompétence reste également\n"
	.string "inchangée…$"

Route117_Text_DerekPostBattle:
	.string "Tout ce que j'ai fait, c'est suivre\n"
	.string "mon cœur, et maintenant ils\p"
	.string "m'appellent un BUG MANIAC…\n"
	.string "Pourtant, je suis un expert en BUG\p"
	.string "POKéMON, donc c'est tout à fait\n"
	.string "naturel qu'ils m'appellent un BUG\p"
	.string "MANIAC.$"

Route117_Text_AnnaIntro:
	.string "ANNA : Je suis avec ma jolie\n"
	.string "partenaire étudiante junior. Je\p"
	.string "dois faire le bien !$"

Route117_Text_AnnaDefeat:
	.string "ANNA : Je suis avec ma jolie\n"
	.string "partenaire étudiante junior !\p"
	.string "Laissez-moi gagner !$"

Route117_Text_AnnaPostBattle:
	.string "ANNA : Vos POKéMON ont de bonnes\n"
	.string "combinaisons. Je dirais que tu es\p"
	.string "juste derrière nous !$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA : Nous ne pouvons pas rester\n"
	.string "sans rien faire ! Vous reviendrez,\p"
	.string "n'est-ce pas ?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA : Si tu veux nous combattre,\n"
	.string "amène deux POKéMON avec toi.$"

Route117_Text_MegIntro:
	.string "MEG : Je vais rejoindre mon\n"
	.string "partenaire étudiant super senior et\p"
	.string "te battre !$"

Route117_Text_MegDefeat:
	.string "MEG : Ah non ! Je suis désolé, ANNA\n"
	.string "! Je t'ai laissé tomber…$"

Route117_Text_MegPostBattle:
	.string "MEG : J'ai entraîné ANNA vers le\n"
	.string "bas… Si je ne l'avais pas fait,\p"
	.string "elle aurait gagné !$"

Route117_Text_MegNotEnoughMons:
	.string "MEG : Tu n'as qu'un seul POKéMON ?\n"
	.string "Nous ne pouvons donc pas nous\p"
	.string "battre contre vous. Nous voulons\n"
	.string "avoir une bataille à 2 contre 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA : Je ne peux pas continuer à\n"
	.string "perdre devant mon partenaire\p"
	.string "junior, n'est-ce pas ?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA : Je n'arrivais pas à entrer\n"
	.string "dans le rythme.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA : Vos POKéMON ont de bonnes\n"
	.string "combinaisons. Je dirais que tu es\p"
	.string "juste derrière nous !$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA : Si tu veux nous combattre,\n"
	.string "amène deux POKéMON avec toi.$"

Route117_Text_MegRematchIntro:
	.string "MEG : Je vais rejoindre mon\n"
	.string "partenaire principal et gagner\p"
	.string "cette fois !$"

Route117_Text_MegRematchDefeat:
	.string "MEG : Trop fort !$"

Route117_Text_MegPostRematch:
	.string "MEG : Je me suis battu avec mon\n"
	.string "partenaire principal, mais nous\p"
	.string "avons perdu… C'est tellement\n"
	.string "décourageant…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG : Tu n'as qu'un seul POKéMON ?\n"
	.string "Nous ne pouvons donc pas nous\p"
	.string "battre contre vous. Nous voulons\n"
	.string "avoir une bataille à 2 contre 2.$"

Route117_Text_MelinaIntro:
	.string "N'est-ce pas sympa ? Se battre en\n"
	.string "regardant de jolies fleurs ?$"

Route117_Text_MelinaDefeat:
	.string "Oh, c'est assez impressionnant !$"

Route117_Text_MelinaPostBattle:
	.string "C'est merveilleux de faire du\n"
	.string "jogging en regardant les fleurs.$"

Route117_Text_BrandiIntro:
	.string "Laissez-moi vous démontrer le\n"
	.string "pouvoir caché dans un POKéMON\p"
	.string "PSYCHIQUE !$"

Route117_Text_BrandiDefeat:
	.string "Étonnant !$"

Route117_Text_BrandiPostBattle:
	.string "Les POKéMON PSYCHIQUES sont\n"
	.string "complexes. Tu devrais essayer d'en\p"
	.string "attraper.$"

Route117_Text_AishaIntro:
	.string "Concentrez-vous sur la victoire.\n"
	.string "C'est comme ça que je me bats !$"

Route117_Text_AishaDefeat:
	.string "Je ne perds pas de temps à être en\n"
	.string "colère suite à une défaite, je\p"
	.string "préfère m'entraîner.$"

Route117_Text_AishaPostBattle:
	.string "Je pense que si vous craignez de\n"
	.string "perdre, vous avez plus de chances\p"
	.string "de perdre.$"

Route118_Text_RoseIntro:
	.string "L'arôme des fleurs a un pouvoir\n"
	.string "magique. Il nous nettoie corps et\p"
	.string "âme.$"

Route118_Text_RoseDefeat:
	.string "Oh, mon Dieu. J'ai l'impression\n"
	.string "d'avoir perdu.$"

Route118_Text_RosePostBattle:
	.string "Fleurs, POKéMON… J'aime tout ce qui\n"
	.string "sent bon. Des choses puantes… je\p"
	.string "vais passer.$"

Route118_Text_RoseRegister:
	.string "Reniflez… Cette odeur, c'est un\n"
	.string "POKéNAV ! Nous devons nous\p"
	.string "inscrire!$"

Route118_Text_RoseRematchIntro:
	.string "Avez-vous été attiré ici par le\n"
	.string "doux arôme ?$"

Route118_Text_RoseRematchDefeat:
	.string "Le pouvoir de l'arôme… Cela ne\n"
	.string "semblait pas faire grand-chose.$"

Route118_Text_RosePostRematch:
	.string "Si vous utilisez correctement un\n"
	.string "arôme sucré, POKéMON sera attiré\p"
	.string "par celui-ci.$"

Route118_Text_PerryIntro:
	.string "DES POKéMON OISEAU qui VOLENT\n"
	.string "élégamment dans le ciel… Ce sont\p"
	.string "les meilleurs !$"

Route118_Text_PerryDefeat:
	.string "Urgh… je me suis écrasé…$"

Route118_Text_PerryPostBattle:
	.string "Vous avez un super POKéMON. Je vais\n"
	.string "devoir mieux entraîner le mien.$"

Route118_Text_ChesterIntro:
	.string "Prendre la fuite! Mon POKéMON\n"
	.string "OISEAU !$"

Route118_Text_ChesterDefeat:
	.string "Ils ont pris leur envol…$"

Route118_Text_ChesterPostBattle:
	.string "S'ils devenaient plus forts, ils\n"
	.string "pourraient voler plus librement…$"

Route118_Text_BarnyIntro:
	.string "Je suis PÊCHEUR, mais aussi\n"
	.string "DRESSEUR. Je relance le\p"
	.string "POKéMON que j'ai attrapé.$"

Route118_Text_BarnyDefeat:
	.string "Je pensais que j'allais bien dans\n"
	.string "mon entraînement…$"

Route118_Text_BarnyPostBattle:
	.string "Je ne pouvais pas gagner en\n"
	.string "entraînant POKéMON pendant que je\p"
	.string "pêchais… Est-ce que je faisais les\n"
	.string "choses dans la demi-mesure ?$"

Route118_Text_WadeIntro:
	.string "Pour les PÊCHEURS, l’équipement est\n"
	.string "la clé. Mais pour les\p"
	.string "DRESSEURS, les ingrédients\n"
	.string "clés sont POKéMON et le cœur, bien\p"
	.string "sûr !$"

Route118_Text_WadeDefeat:
	.string "J'ai eu le cœur battu ?$"

Route118_Text_WadePostBattle:
	.string "À bien y penser, la pêche est une\n"
	.string "bataille entre un PÊCHEUR et un\p"
	.string "POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Laisse ma mélodie bercer ton âme !$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Une guitare électrique ne doit pas\n"
	.string "toujours être bruyante… On peut la\p"
	.string "gratter pour faire ressortir cette\n"
	.string "mélodie émouvante…$"

Route118_Text_DaltonRegister:
	.string "Quand je compose de meilleures\n"
	.string "mélodies, tu dois venir écouter,\p"
	.string "d'accord ?$"

Route118_Text_DaltonRematchIntro:
	.string "Une mélodie de mon POKéMON et de\n"
	.string "moi… Laissez-nous la livrer à votre\p"
	.string "âme.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quand je joue, mes émotions\n"
	.string "devraient vous parvenir à travers\p"
	.string "ma guitare électrique…$"

Route118_Text_DeandreIntro:
	.string "Allez! Allez! Allez! POKéMON 1, 2\n"
	.string "et 3 !$"

Route118_Text_DeandreDefeat:
	.string "Entrez, POKéMON ! Êtes-vous\n"
	.string "d'accord? POKéMON 1, 2 et 3 ?!$"

Route118_Text_DeandrePostBattle:
	.string "N'est-ce pas cool d'avoir une\n"
	.string "équipe de combat POKéMON ? Vous\p"
	.string "pouvez me copier, ça ne me dérange\n"
	.string "pas !$"

Route119_Text_BrentIntro:
	.string "Nous sommes le CERCLE MIMIC ! Nous\n"
	.string "IMITONS ce que vous faites !$"

Route119_Text_BrentDefeat:
	.string "Oups! J'ai perdu !$"

Route119_Text_BrentPostBattle:
	.string "Qu'y a-t-il de si bon dans le\n"
	.string "mimétisme ? Fufufu… Tu ne\p"
	.string "comprendras jamais…$"

Route119_Text_DonaldIntro:
	.string "Alors on se retrouve enfin ! Mon\n"
	.string "BUG POKéMON vous tiendra compagnie\p"
	.string "!$"

Route119_Text_DonaldDefeat:
	.string "J'aurais aimé que nous ne nous\n"
	.string "soyons jamais rencontrés…$"

Route119_Text_DonaldPostBattle:
	.string "Je veux vous imiter encore\n"
	.string "davantage. Pouvez-vous vous\p"
	.string "dépêcher et bouger ?$"

Route119_Text_TaylorIntro:
	.string "Si vous avancez, nous avançons. Si\n"
	.string "vous tournez à droite, nous\p"
	.string "tournons aussi…$"

Route119_Text_TaylorDefeat:
	.string "Mais si tu gagnes, je perds…$"

Route119_Text_TaylorPostBattle:
	.string "Je ne peux pas vous imiter en train\n"
	.string "de gagner le match. C'est tout\p"
	.string "simplement impossible… Ça me\n"
	.string "brûle…$"

Route119_Text_DougIntro:
	.string "Ouais, tu m'as enfin attrapé ! Ou\n"
	.string "essayais-tu de m'éviter ?$"

Route119_Text_DougDefeat:
	.string "Oups, c'était un super match !$"

Route119_Text_DougPostBattle:
	.string "Nous sommes le CERCLE MIMIC !\n"
	.string "J'espère que vous avez apprécié\p"
	.string "notre performance.$"

Route119_Text_GregIntro:
	.string "Vous ne savez pas qui je suis,\n"
	.string "n'est-ce pas ? Mais je ne vous\p"
	.string "connais pas non plus. Alors, nous\n"
	.string "allons nous battre !$"

Route119_Text_GregDefeat:
	.string "Tu es plutôt fort !$"

Route119_Text_GregPostBattle:
	.string "Jusqu'à ce que vous partiez quelque\n"
	.string "part, nous continuerons à imiter\p"
	.string "chacun de vos mouvements.$"

Route119_Text_KentIntro:
	.string "Le MIMIC CIRCLE a été formé par des\n"
	.string "personnes qui aiment MIMIC. Une\p"
	.string "bataille commence dès l'instant où\n"
	.string "nous nous rencontrons !$"

Route119_Text_KentDefeat:
	.string "J'abandonne !$"

Route119_Text_KentPostBattle:
	.string "Ne rejoindriez-vous pas notre MIMIC\n"
	.string "CIRCLE ?$"

Route119_Text_JacksonIntro:
	.string "Qui possède les connaissances et la\n"
	.string "technique pour survivre ? POKéMON\p"
	.string "RANGERS, c'est qui !$"

Route119_Text_JacksonDefeat:
	.string "Je n'avais pas assez de\n"
	.string "connaissances POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "Pour rompre avec la civilisation et\n"
	.string "éveiller l’esprit sauvage qui\p"
	.string "sommeille en vous ! C'est notre\n"
	.string "vision.$"

Route119_Text_JacksonRegister:
	.string "J'espère que vous me donnerez une\n"
	.string "revanche sans vous moquer de mon\p"
	.string "manque de connaissances.$"

Route119_Text_JacksonRematchIntro:
	.string "Je vais retrouver mon esprit\n"
	.string "sauvage en étant avec POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Vous êtes resté fort !$"

Route119_Text_JacksonPostRematch:
	.string "Croyez en votre POKéMON. Croyez en\n"
	.string "vous. La route se dévoilera à\p"
	.string "vous.$"

Route119_Text_CatherineIntro:
	.string "Oh? Regarde toi. Pour quelqu'un en\n"
	.string "aventure, vous voyagez terriblement\p"
	.string "léger.$"

Route119_Text_CatherineDefeat:
	.string "Les accidents surviennent quand on\n"
	.string "n'est pas préparé !$"

Route119_Text_CatherinePostBattle:
	.string "Vous voyagez léger mais vous avez\n"
	.string "tout ce dont vous avez besoin. Vous\p"
	.string "êtes également au top mentalement\n"
	.string "et physiquement.$"

Route119_Text_CatherineRegister:
	.string "Avez-vous un POKéNAV ? C'est un\n"
	.string "outil indispensable pour tout\p"
	.string "DRESSEUR. Oh, tu en as un !\n"
	.string "Alors inscrivons-nous les uns les\p"
	.string "autres !$"

Route119_Text_CatherineRematchIntro:
	.string "Comment se passe votre voyage avec\n"
	.string "POKéMON ?$"

Route119_Text_CatherineRematchDefeat:
	.string "Il me manque encore quelque chose…$"

Route119_Text_CatherinePostRematch:
	.string "De la même manière que vous, en\n"
	.string "tant qu'DRESSEUR, comptez sur votre\p"
	.string "POKéMON, votre POKéMON compte sur\n"
	.string "vous.$"

Route119_Text_HughIntro:
	.string "Le vaste ciel recèle des promesses\n"
	.string "incalculables ! Rien ne peut se\p"
	.string "comparer à l’exaltation du vol !$"

Route119_Text_HughDefeat:
	.string "À terre et dehors !$"

Route119_Text_HughPostBattle:
	.string "Mon BIRD POKéMON a réalisé mes\n"
	.string "rêves de voler !$"

Route119_Text_PhilIntro:
	.string "Je vais vous montrer mon véritable\n"
	.string "potentiel et celui de mon POKéMON\p"
	.string "OISEAU !$"

Route119_Text_PhilDefeat:
	.string "Nous manquions de potentiel…$"

Route119_Text_PhilPostBattle:
	.string "Depuis que je suis petit, j'ai\n"
	.string "toujours admiré BIRD POKéMON…$"

Route119_Text_YasuIntro:
	.string "Me cacher dans l’ombre et vivre\n"
	.string "dans l’obscurité… Tel est mon\p"
	.string "destin. Je sors pour vous défier !$"

Route119_Text_YasuDefeat:
	.string "J'avoue ma défaite !$"

Route119_Text_YasuPostBattle:
	.string "Ceux qui sont vaincus au combat se\n"
	.string "retirent tranquillement dans\p"
	.string "l’ombre. Ça aussi, c'est le\n"
	.string "destin…$"

Route119_Text_TakashiIntro:
	.string "Si vous n'êtes pas sur vos gardes,\n"
	.string "vous allez souffrir !$"

Route119_Text_TakashiDefeat:
	.string "Tu es étonnamment bon !$"

Route119_Text_TakashiPostBattle:
	.string "Mon attaque surprise s'est soldée\n"
	.string "par un échec…$"

Route119_Text_HideoIntro:
	.string "Pour cacher un arbre, utilisez une\n"
	.string "forêt !$"

Route119_Text_HideoDefeat:
	.string "Je m'incline devant votre\n"
	.string "supériorité.$"

Route119_Text_HideoPostBattle:
	.string "Pour cacher un arbre, utilisez une\n"
	.string "forêt ! Pour cacher un POKéMON,\p"
	.string "utilisez un POKéMON ! Il n’y a pas\n"
	.string "de sens profond et caché à cela.$"

Route119_Text_ChrisIntro:
	.string "Tu m'as parlé… Alors tu as envie de\n"
	.string "me défier ! Bien sûr! Je vais\p"
	.string "essayer le POKéMON que j'ai attrapé\n"
	.string "en SURF !$"

Route119_Text_ChrisDefeat:
	.string "Je n'ai aucune idée de ce qu'il\n"
	.string "faut pour gagner.$"

Route119_Text_ChrisPostBattle:
	.string "Faire un SURF sur mon POKéMON… Puis\n"
	.string "pêcher sur son dos… C'est un moment\p"
	.string "indescriptible de luxe !$"

Route119_Text_FabianIntro:
	.string "Frappez-moi avec un accord de\n"
	.string "puissance ! La victoire est mienne!\p"
	.string "C'est notre moment de briller,\n"
	.string "whoa, ouais !$"

Route119_Text_FabianDefeat:
	.string "Tu m'as montré qui est le patron !\n"
	.string "Nous devrons assumer la perte, oh,\p"
	.string "non !$"

Route119_Text_FabianPostBattle:
	.string "Frappez-moi avec un autre accord de\n"
	.string "puissance ! Laisse-moi tranquille!\p"
	.string "Votre victoire, vous devez l'expier\n"
	.string "!$"

Route119_Text_DaytonIntro:
	.string "Ho ho ho! J'aime les\n"
	.string "DRESSEURS pour enfants !\p"
	.string "Amusons-nous bien !$"

Route119_Text_DaytonDefeat:
	.string "Tu es vraiment incroyable !\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Ho ho ho! Je vais essayer d'imiter\n"
	.string "le dynamisme des DRESSEURS pour\p"
	.string "enfants comme vous !$"

Route119_Text_RachelIntro:
	.string "Où que je sois, j'ai toujours mon\n"
	.string "parasol à la main.$"

Route119_Text_RachelDefeat:
	.string "Oh, mais… Ce n'est pas juste.$"

Route119_Text_RachelPostBattle:
	.string "Vous demandez si mon parasol est\n"
	.string "lourd ? Votre SAC est rempli de\p"
	.string "plus de déchets que je n'en ai\n"
	.string "jamais transporté.$"

Route120_Text_ColinIntro:
	.string "Avez-vous des capacités qui peuvent\n"
	.string "frapper un POKéMON volant ?$"

Route120_Text_ColinDefeat:
	.string "Tu as plané au-dessus de moi !$"

Route120_Text_ColinPostBattle:
	.string "Le mouvement FLY est pratique, vous\n"
	.string "ne trouvez pas ? Pendant que le\p"
	.string "POKéMON vole, presque aucun\n"
	.string "mouvement ne peut le toucher.$"

Route120_Text_RobertIntro:
	.string "Mon POKéMON est fort ! Et le vôtre\n"
	.string "?$"

Route120_Text_RobertDefeat:
	.string "Vos POKéMON étaient plus forts…$"

Route120_Text_RobertPostBattle:
	.string "Un POKéMON qui grandit\n"
	.string "régulièrement est celui sur lequel\p"
	.string "vous pouvez compter.$"

Route120_Text_RobertRegister:
	.string "On peut compter sur vous pour vous\n"
	.string "améliorer. J'aimerais vous inscrire\p"
	.string "dans mon POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "Un POKéMON qui grandit\n"
	.string "régulièrement est celui sur lequel\p"
	.string "vous pouvez compter.$"

Route120_Text_RobertRematchDefeat:
	.string "Vos POKéMON sont vraiment forts.$"

Route120_Text_RobertPostRematch:
	.string "Mes POKéMON deviennent plus forts.\n"
	.string "Je dois aussi devenir plus fort.$"

Route120_Text_LorenzoIntro:
	.string "Je vais vérifier vos POKéMON et\n"
	.string "voir s'ils sont adaptés à\p"
	.string "l'extérieur.$"

Route120_Text_LorenzoDefeat:
	.string "Avec un POKéMON aussi puissant,\n"
	.string "vous ne risquez pas d'avoir besoin\p"
	.string "d'être secouru !$"

Route120_Text_LorenzoPostBattle:
	.string "Voyager où bon vous semble avec\n"
	.string "POKéMON… C'est le bonheur d'être\p"
	.string "DRESSEUR.$"

Route120_Text_JennaIntro:
	.string "Comment est ta forme physique ? Si\n"
	.string "vous n'êtes pas en forme, vous\p"
	.string "pourriez vivre des moments\n"
	.string "difficiles dans des situations\p"
	.string "critiques.$"

Route120_Text_JennaDefeat:
	.string "Je suis totalement en forme, mais…$"

Route120_Text_JennaPostBattle:
	.string "L'entraînement physique fait partie\n"
	.string "de ma routine. Je cours toujours\p"
	.string "avec mon POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … … … … … … … … Vous voulez\n"
	.string "vous battre ?$"

Route120_Text_JeffreyDefeat:
	.string "Je l'ai perdu…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … … … … … … … … Je ferai\n"
	.string "plus d'efforts…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … … … … … … … … Avez-vous\n"
	.string "un POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … … … … … … … … Vous voulez\n"
	.string "vous battre à nouveau ?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … … J'ai encore perdu…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … … … … … … … … Je ferai\n"
	.string "plus d'efforts… Pour mon précieux\p"
	.string "BUG POKéMON…$"

Route120_Text_JenniferIntro:
	.string "Les POKéMON possèdent de nombreuses\n"
	.string "capacités spéciales. Si vous\p"
	.string "souhaitez devenir un DRESSEUR\n"
	.string "de premier ordre, renseignez-vous\p"
	.string "sur eux.$"

Route120_Text_JenniferDefeat:
	.string "Vous réfléchissez évidemment.$"

Route120_Text_JenniferPostBattle:
	.string "Les capacités spéciales de POKéMON\n"
	.string "feront changer les styles de\p"
	.string "combat.$"

Route120_Text_ChipIntro:
	.string "Qui peux-tu être? Êtes-vous\n"
	.string "peut-être à la recherche de ruines\p"
	.string "antiques qui, selon la rumeur,\n"
	.string "pourraient exister selon la légende\p"
	.string "?$"

Route120_Text_ChipDefeat:
	.string "Quel revers honteux…$"

Route120_Text_ChipPostBattle:
	.string "Ce rocher géant… J’aimerais croire\n"
	.string "qu’il peut effectivement contenir\p"
	.string "des ruines antiques. Mais je ne\n"
	.string "vois pas d'entrée.$"

Route120_Text_ClarissaIntro:
	.string "Pourquoi je porte ce parasol ? Je\n"
	.string "te dirai si tu peux gagner contre\p"
	.string "moi.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasol ne peut pas parer les\n"
	.string "attaques POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Je ne pense pas qu'un fort soleil\n"
	.string "soit bon pour mon POKéMON. Alors je\p"
	.string "les protège avec mon parasol.$"

Route120_Text_AngelicaIntro:
	.string "Moi, POKéMON et mon parasol… Si\n"
	.string "l'un d'entre eux manque, l'image de\p"
	.string "la beauté sera gâchée.$"

Route120_Text_AngelicaDefeat:
	.string "Tu as complètement gâché ma\n"
	.string "beauté…$"

Route120_Text_AngelicaPostBattle:
	.string "Un parasol ne vous conviendrait pas\n"
	.string "du tout. Eh bien, quelque chose\p"
	.string "comme ça ne ferait que vous gêner.$"

Route120_Text_KeigoIntro:
	.string "Je vais adopter les mouvements de\n"
	.string "POKéMON et créer de nouvelles\p"
	.string "techniques ninja.$"

Route120_Text_KeigoDefeat:
	.string "La création de nouvelles techniques\n"
	.string "ninja n'est qu'un rêve lointain…$"

Route120_Text_KeigoPostBattle:
	.string "Peut-être que je devrais faire mon\n"
	.string "apprentissage auprès d'un ninja\p"
	.string "sensei.$"

Route120_Text_RileyIntro:
	.string "Nous, les ninjas, nous cachons sous\n"
	.string "nos capes de camouflage. Je parie\p"
	.string "que tu ne savais pas où j'étais !$"

Route120_Text_RileyDefeat:
	.string "J'ai perdu! Je devrais camoufler ma\n"
	.string "honte !$"

Route120_Text_RileyPostBattle:
	.string "Nos capes de camouflage sont toutes\n"
	.string "faites à la main.$"

Route120_Text_CallieIntro:
	.string "Si vous n’y prêtez pas attention,\n"
	.string "vous pourriez vous blesser !$"

Route120_Text_CallieDefeat:
	.string "Aie! C'est moi qui ai été blessé.$"

Route120_Text_CalliePostBattle:
	.string "Je me demande… Dois-je faire\n"
	.string "évoluer mon POKéMON ? Mais ils sont\p"
	.string "mignons comme ils sont.$"

Route120_Text_LeonelIntro:
	.string "Votre POKéMON de fête… En avez-vous\n"
	.string "différents types ?$"

Route120_Text_LeonelDefeat:
	.string "J'ai vu votre politique en action\n"
	.string "!$"

Route120_Text_LeonelPostBattle:
	.string "Je pense que c'est génial que tu\n"
	.string "sois si fort en combattant ton\p"
	.string "POKéMON préféré.$"

Route121_Text_VanessaIntro:
	.string "Veux-tu jouer avec mon\n"
	.string "délicieusement joli POKéMON ?$"

Route121_Text_VanessaDefeat:
	.string "Ce n'est pas ce que je voulais dire\n"
	.string "!$"

Route121_Text_VanessaPostBattle:
	.string "Je vais à un CONCOURS à LILYCOVE.\n"
	.string "Mon POKéMON ne devrait avoir aucun\p"
	.string "problème à balayer la MASTER\n"
	.string "CLASS.$"

Route121_Text_WalterIntro:
	.string "Avec mon POKéMON, j'ai voyagé aux\n"
	.string "quatre coins du monde. On pourrait\p"
	.string "dire que j'ai une certaine\n"
	.string "confiance en mes capacités.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien joué.$"

Route121_Text_WalterPostBattle:
	.string "J'aimerais à nouveau faire le tour\n"
	.string "du monde avec mon POKéMON.$"

Route121_Text_WalterRegister:
	.string "Vos prouesses POKéMON sont\n"
	.string "remarquables. Permettez-moi de vous\p"
	.string "enregistrer comme souvenir.$"

Route121_Text_WalterRematchIntro:
	.string "Avec mon POKéMON, j'ai voyagé aux\n"
	.string "quatre coins du monde. On pourrait\p"
	.string "dire que j'ai une certaine\n"
	.string "confiance en mes capacités.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien joué.$"

Route121_Text_WalterPostRematch:
	.string "Votre POKéMON et vous… Vos\n"
	.string "prouesses ensemble seront\p"
	.string "considérées comme fortes, même à\n"
	.string "l'étranger.$"

Route121_Text_TammyIntro:
	.string "Il existe des pouvoirs au-delà de\n"
	.string "notre compréhension dans le monde…$"

Route121_Text_TammyDefeat:
	.string "J'ai perdu…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE… Il y a un pouvoir\n"
	.string "mystérieux à l’œuvre là-bas…$"

Route121_Text_KateIntro:
	.string "KATE : Ensemble, nous n'avons peur\n"
	.string "de rien ! Nous démontrerons à quel\p"
	.string "point nous sommes durs !$"

Route121_Text_KateDefeat:
	.string "KATE : J'ai tout gâché devant mon\n"
	.string "partenaire étudiant junior…$"

Route121_Text_KatePostBattle:
	.string "KATE : Quand quelqu'un compte sur\n"
	.string "moi, j'ai envie d'avoir l'air cool\p"
	.string "devant lui…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE : Si vous n'avez qu'un seul\n"
	.string "POKéMON, nous ne pouvons pas nous\p"
	.string "battre avec vous. Ce serait de\n"
	.string "l'intimidation.$"

Route121_Text_JoyIntro:
	.string "JOY : Ensemble, nous n'avons peur\n"
	.string "de rien ! Nous démontrerons à quel\p"
	.string "point nous sommes durs !$"

Route121_Text_JoyDefeat:
	.string "JOY : S'il te plaît, pardonne-moi,\n"
	.string "KATE !$"

Route121_Text_JoyPostBattle:
	.string "JOY : Ehéhé, je vais devoir\n"
	.string "m'entraîner à nouveau avec KATE, ma\p"
	.string "partenaire étudiante senior.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOIE : Vous avez besoin d'au moins\n"
	.string "deux POKéMON si vous voulez nous\p"
	.string "défier !$"

Route121_Text_JessicaIntro:
	.string "Arrêt! Regardez bien mon précieux\n"
	.string "POKéMON !$"

Route121_Text_JessicaDefeat:
	.string "Oh, comment oses-tu ! Ne le prends\n"
	.string "pas si au sérieux !$"

Route121_Text_JessicaPostBattle:
	.string "Peut-être que j'irai attraper plus\n"
	.string "de POKéMON au SAFARI.$"

Route121_Text_JessicaRegister:
	.string "J'ai été calme avec toi cette\n"
	.string "fois-ci ! Ce ne sera pas comme ça\p"
	.string "la prochaine fois !$"

Route121_Text_JessicaRematchIntro:
	.string "Mon précieux POKéMON a grandi !\n"
	.string "Regardez bien !$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, comment oses-tu ! Vous n'allez\n"
	.string "toujours pas y aller doucement !$"

Route121_Text_JessicaPostRematch:
	.string "Peut-être que j'irai attraper plus\n"
	.string "de POKéMON au SAFARI.$"

Route121_Text_CristinIntro:
	.string "J'ai cette routine. Battez cinq\n"
	.string "DRESSEURS par jour. Devinez quoi?\p"
	.string "Vous êtes le numéro cinq !$"

Route121_Text_CristinDefeat:
	.string "Non! Tu es horrible !$"

Route121_Text_CristinPostBattle:
	.string "Je ne m'attendais pas à perdre\n"
	.string "aussi facilement… Je gagnerai la\p"
	.string "prochaine fois !$"

Route121_Text_CristinRegister:
	.string "C'était une humiliation totale ! Je\n"
	.string "ne t'oublierai pas… Remettez votre\p"
	.string "POKéNAV !$"

Route121_Text_CristinRematchIntro:
	.string "J'ai cette nouvelle routine. Battez\n"
	.string "dix DRESSEURS par jour. Devinez\p"
	.string "quoi? Tu es le numéro dix !$"

Route121_Text_CristinRematchDefeat:
	.string "Attendez! C'est sale! J'exige une\n"
	.string "revanche !$"

Route121_Text_CristinPostRematch:
	.string "Un adversaire que je ne peux tout\n"
	.string "simplement pas battre… Snivel… Je\p"
	.string "ne peux pas croire que cela\n"
	.string "arrive…$"

Route121_Text_CaleIntro:
	.string "Tu ne vois pas que j'ai tout ça\n"
	.string "avec moi ? Malgré cela, vous\p"
	.string "insistez toujours pour que nous\n"
	.string "nous battions ?$"

Route121_Text_CaleDefeat:
	.string "Bien sûr, j'ai perdu ! Je tiens des\n"
	.string "trucs à deux mains !$"

Route121_Text_CalePostBattle:
	.string "J'ai acheté trop de trucs au\n"
	.string "LILYCOVE DEPT. MAGASIN. C'est au\p"
	.string "bout de la route. J'aurais aimé\n"
	.string "avoir un SAC comme le vôtre.$"

Route121_Text_MylesIntro:
	.string "Il n'y a rien que j'aime plus que\n"
	.string "découvrir les POKéMON des autres !$"

Route121_Text_MylesDefeat:
	.string "Super génial !$"

Route121_Text_MylesPostBattle:
	.string "Ils sont super, tes POKéMON !\n"
	.string "Comment les élever ?$"

Route121_Text_PatIntro:
	.string "Je veux que tout le monde voie le\n"
	.string "POKéMON que j'ai élevé !$"

Route121_Text_PatDefeat:
	.string "Ouah! Spectaculaire!$"

Route121_Text_PatPostBattle:
	.string "J'élève chaque POKéMON avec le même\n"
	.string "amour et le même soin : je ne\p"
	.string "choisis pas de favoris.$"

Route121_Text_MarcelIntro:
	.string "Mes POKéMON n'ont jamais goûté à la\n"
	.string "défaite ! Lors de leur prochaine\p"
	.string "victoire, je les inscris à des\n"
	.string "CONCOURS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, maintenant, que s'est-il passé\n"
	.string "ici ?$"

Route121_Text_MarcelPostBattle:
	.string "Je devrai peut-être entraîner\n"
	.string "davantage mon gang avant de\p"
	.string "participer à un CONCOURS.$"

Route123_Text_WendyIntro:
	.string "Vous voulez déterminer votre force\n"
	.string "? Je serai le test !$"

Route123_Text_WendyDefeat:
	.string "Vous avez réussi avec brio !$"

Route123_Text_WendyPostBattle:
	.string "Pour me surpasser… Ta force est\n"
	.string "merveilleuse !$"

Route123_Text_BraxtonIntro:
	.string "Vous semblez avoir une grande\n"
	.string "collection de BADGES GYM.\p"
	.string "Laisse-moi voir si tu es réellement\n"
	.string "digne de ces BADGES !$"

Route123_Text_BraxtonDefeat:
	.string "Oh, tu en es digne, d'accord !$"

Route123_Text_BraxtonPostBattle:
	.string "Vous avez porté vos BADGES avec\n"
	.string "fierté lors de ce match !$"

Route123_Text_VioletIntro:
	.string "On dit que les bons moments sont\n"
	.string "remplis de bons arômes.$"

Route123_Text_VioletDefeat:
	.string "Oh… je sens le parfum amer de la\n"
	.string "misère…$"

Route123_Text_VioletPostBattle:
	.string "Le jardin du BERRY MASTER regorge\n"
	.string "de parfums exaltants.$"

Route123_Text_CameronIntro:
	.string "Être médium est une question de\n"
	.string "volonté. J'ai décidé de ne perdre\p"
	.string "contre personne. Cela me rend fort\n"
	.string "!$"

Route123_Text_CameronDefeat:
	.string "Je me sens triste…$"

Route123_Text_CameronPostBattle:
	.string "Être médium est une question de\n"
	.string "volonté. Je pensais que je ne\p"
	.string "perdrais pas contre toi…$"

Route123_Text_CameronRegister:
	.string "Je le sens ! Toi et moi nous\n"
	.string "battrons à nouveau ! Cependant, je\p"
	.string "ne peux pas dire si je vais gagner…\n"
	.string "Voyons votre POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Je me suis convaincu que je ne\n"
	.string "perdrai plus. Cela me rend fort !$"

Route123_Text_CameronRematchDefeat:
	.string "Je me sens triste…$"

Route123_Text_CameronPostRematch:
	.string "Je devrais m'entraîner à MT. PYRE…\n"
	.string "Je ne te battrai jamais de cette\p"
	.string "façon…$"

Route123_Text_JackiIntro:
	.string "Ne soyez pas trop heureux si votre\n"
	.string "POKéMON développe des pouvoirs\p"
	.string "psychiques. Vous devez affiner ces\n"
	.string "pouvoirs pour les rendre vraiment\p"
	.string "utiles.$"

Route123_Text_JackiDefeat:
	.string "Débordé !$"

Route123_Text_JackiPostBattle:
	.string "Nous avons tous des pouvoirs\n"
	.string "psychiques. Nous avons simplement\p"
	.string "oublié comment les utiliser.$"

Route123_Text_JackiRegister:
	.string "J'aimerais te faire face à nouveau.\n"
	.string "Est-ce que ça te va ?$"

Route123_Text_JackiRematchIntro:
	.string "Avez-vous réveillé les pouvoirs\n"
	.string "psychiques en vous ?$"

Route123_Text_JackiRematchDefeat:
	.string "Étonnant !$"

Route123_Text_JackiPostRematch:
	.string "Votre pouvoir avec POKéMON… Cela\n"
	.string "pourrait aussi être un pouvoir\p"
	.string "psychique.$"

Route123_Text_MiuIntro:
	.string "MIU : Bonjour, DRESSEUR.\n"
	.string "J'espère que votre POKéMON ne\p"
	.string "pleurera pas quand il perdra.$"

Route123_Text_MiuDefeat:
	.string "MIU : Oh-oh, nous avons perdu.$"

Route123_Text_MiuPostBattle:
	.string "MIU : DRESSEUR, vos POKéMON sont\n"
	.string "forts parce que vous êtes amis.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU : Ce n'est pas amusant de se\n"
	.string "battre si vous n'avez pas deux\p"
	.string "POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI : D’accord ! On bat le POKéMON\n"
	.string "du DRESSEUR !$"

Route123_Text_YukiDefeat:
	.string "YUKI : Oh-oh, nous avons perdu.$"

Route123_Text_YukiPostBattle:
	.string "YUKI : Pourquoi es-tu si fort ?\n"
	.string "Nous n'avons jamais perdu\p"
	.string "auparavant.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI : Ce n'est pas amusant de se\n"
	.string "battre si vous n'avez pas deux\p"
	.string "POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE… Où dorment les esprits de\n"
	.string "POKéMON… Votre POKéMON dormira-t-il\p"
	.string "?$"

Route123_Text_KindraDefeat:
	.string "Débordant de vitalité…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE… Là où dorment les esprits\n"
	.string "de POKéMON… Il doit déborder d'un\p"
	.string "pouvoir qui apaise les esprits…$"

Route123_Text_FernandoIntro:
	.string "Je vais éteindre vos lumières\n"
	.string "pendant que j'écoute cette chanson\p"
	.string "!$"

Route123_Text_FernandoDefeat:
	.string "Hé, attends ! Je jouais encore\n"
	.string "l'intro !$"

Route123_Text_FernandoPostBattle:
	.string "Vous êtes stable comme un roc.\n"
	.string "J'aimerais écrire une chanson sur\p"
	.string "toi.$"

Route123_Text_FernandoRegister:
	.string "La prochaine fois, prêtez vos\n"
	.string "oreilles au son complet,\p"
	.string "voulez-vous ?$"

Route123_Text_FernandoRematchIntro:
	.string "Aujourd'hui, c'est le jour où je\n"
	.string "vais le faire ! J'éteindrai vos\p"
	.string "lumières avant de finir de chanter\n"
	.string "ma chanson !$"

Route123_Text_FernandoRematchDefeat:
	.string "Hé, attends ! Je n'ai même pas\n"
	.string "touché le refrain !$"

Route123_Text_FernandoPostRematch:
	.string "Je pensais que tu serais tellement\n"
	.string "captivé par ma musique que tu\p"
	.string "perdrais.$"

Route123_Text_DavisIntro:
	.string "C'est mon génial POKéMON BUG ! Mon\n"
	.string "grand frère me l'a offert.$"

Route123_Text_DavisDefeat:
	.string "Ouah! Tu es méchant !$"

Route123_Text_DavisPostBattle:
	.string "Ne dis pas à mon frère que j'ai\n"
	.string "perdu. Vous devez garder le secret\p"
	.string "!$"

Route123_Text_JazmynIntro:
	.string "Ma confiance sera renforcée en\n"
	.string "battant quelqu'un de visiblement\p"
	.string "fort !$"

Route123_Text_JazmynDefeat:
	.string "Voilà ma confiance…$"

Route123_Text_JazmynPostBattle:
	.string "On dit qu’on ne peut pas juger une\n"
	.string "personne sur son apparence. Mais\p"
	.string "souvent, leur look ne ment pas…$"

Route123_Text_FrederickIntro:
	.string "Bonjour, mon enfant ! Pouvez-vous\n"
	.string "me consacrer un peu de temps ?$"

Route123_Text_FrederickDefeat:
	.string "Ah, un enfant puissant !\n"
	.string "Laissez-moi contribuer à votre\p"
	.string "allocation.$"

Route123_Text_FrederickPostBattle:
	.string "Contribuer à votre allocation ? Le\n"
	.string "prix en argent n'était-il pas\p"
	.string "suffisant ?$"

Route123_Text_AlbertoIntro:
	.string "Je dois vous le dire, les BIRD\n"
	.string "POKéMON sont mon obsession ! Les\p"
	.string "oiseaux, c'est cool ! Ce sont les\n"
	.string "meilleurs !$"

Route123_Text_AlbertoDefeat:
	.string "Même en cas de défaite, les BIRD\n"
	.string "POKéMON sont cool !$"

Route123_Text_AlbertoPostBattle:
	.string "Je récupère les plumes d'OISEAU\n"
	.string "POKéMON qui se dispersent lors des\p"
	.string "combats. Je vais faire un chapeau\n"
	.string "avec des plumes BIRD POKéMON.$"

Route123_Text_EdIntro:
	.string "Lorsqu'il n'y a pas d'DRESSEURS\n"
	.string "dans les parages, je laisse mes\p"
	.string "POKéMON s'affronter. Je les\n"
	.string "regarde.$"

Route123_Text_EdDefeat:
	.string "J'aime bien ton POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Héhé, je swipe tes idées de combat\n"
	.string "! Je pense qu'ils me rendront\p"
	.string "meilleur.$"

Route123_Text_JonasIntro:
	.string "Je suis en embuscade et un DRESSEUR\n"
	.string "a atterri dans mon piège !$"

Route123_Text_JonasDefeat:
	.string "Si tu ne perds pas, comment suis-je\n"
	.string "censé m'amuser en jouant au ninja\p"
	.string "?$"

Route123_Text_JonasPostBattle:
	.string "Je vais tendre une embuscade à un\n"
	.string "DRESSEUR d'apparence plus faible la\p"
	.string "prochaine fois.$"

Route123_Text_KayleyIntro:
	.string "Je viens d'acheter ce parasol. Ma\n"
	.string "gentillesse devrait augmenter d'un\p"
	.string "tiers !$"

Route123_Text_KayleyDefeat:
	.string "Tu es cinq fois meilleur que moi !$"

Route123_Text_KayleyPostBattle:
	.string "Utiliser efficacement les\n"
	.string "accessoires est le secret de\p"
	.string "l’attrait de la mode.$"

Route124_Text_SpencerIntro:
	.string "Hé, tu es perdu en mer ? Si vous\n"
	.string "parvenez à battre mon POKéMON, je\p"
	.string "peux vous servir de pilote.$"

Route124_Text_SpencerDefeat:
	.string "J'ai perdu mes repères au combat !$"

Route124_Text_SpencerPostBattle:
	.string "De nombreuses personnes perdent\n"
	.string "leurs repères en mer. Si vous êtes\p"
	.string "de ce genre, vous devriez vous\n"
	.string "référer à la CARTE du POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hum ! Tu chevauches un POKéMON au\n"
	.string "lieu de nager toi-même… Je suis\p"
	.string "envieux !$"

Route124_Text_RolandDefeat:
	.string "Oh! Je ne peux pas…$"

Route124_Text_RolandPostBattle:
	.string "J'ai froid… Je suis dans l'eau\n"
	.string "depuis trop longtemps… J'aimerais\p"
	.string "pouvoir monter un POKéMON comme\n"
	.string "toi…$"

Route124_Text_JennyIntro:
	.string "Si vous flottez dans la mer comme\n"
	.string "ça, POKéMON vient jouer.$"

Route124_Text_JennyDefeat:
	.string "Oh zut. Je suis parti et j'ai\n"
	.string "perdu.$"

Route124_Text_JennyPostBattle:
	.string "En nageant, j'ai remarqué que\n"
	.string "certains POKéMON attaquent, et\p"
	.string "d'autres se contentent de regarder.\n"
	.string "Je suppose que les POKéMON ont leur\p"
	.string "propre personnalité.$"

Route124_Text_JennyRegister:
	.string "Ce n'est que sur un coup de tête,\n"
	.string "mais peut-être que je vais te\p"
	.string "demander de m'inscrire dans ton\n"
	.string "POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Si vous flottez dans la mer comme\n"
	.string "ça, les DRESSEURS vous mettent au\p"
	.string "défi !$"

Route124_Text_JennyRematchDefeat:
	.string "C'est étrange… j'ai encore perdu…$"

Route124_Text_JennyPostRematch:
	.string "Cela n'a rien à voir avec quoi que\n"
	.string "ce soit, mais je visiterai\p"
	.string "peut-être la TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "Je m'ennuie de nager… Que\n"
	.string "diriez-vous d'une bataille ?$"

Route124_Text_GraceDefeat:
	.string "Je ne savais pas que tu étais aussi\n"
	.string "fort !$"

Route124_Text_GracePostBattle:
	.string "Tous les efforts que vous avez\n"
	.string "déployés ont dû vous rendre aussi\p"
	.string "fort.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… Je plonge profondément\n"
	.string "sous l'eau pour aller profondément\p"
	.string "à l'abri. La plomberie des\n"
	.string "profondeurs est là où j'excelle !$"

Route124_Text_ChadDefeat:
	.string "Profondeur, profondeur,\n"
	.string "profondeur... Je coule...$"

Route124_Text_ChadPostBattle:
	.string "Je sais de source sûre qu'il y a un\n"
	.string "spot de plongée par ici. Cela me\p"
	.string "donne envie d'approfondir à\n"
	.string "nouveau…$"

Route124_Text_LilaIntro:
	.string "LILA : Soupir… Me voilà dans la\n"
	.string "mer, mais qui est avec moi ? Mon\p"
	.string "petit frère! Battons-nous pour ne\n"
	.string "pas avoir à m'attarder là-dessus !$"

Route124_Text_LilaDefeat:
	.string "LILA : ROY ! C'est de ta faute si\n"
	.string "nous avons perdu ! Vous y jouerez\p"
	.string "plus tard !$"

Route124_Text_LilaPostBattle:
	.string "LILA : Soupir… Si seulement ce\n"
	.string "n'était pas mon petit frère à côté\p"
	.string "de moi, mais un gentil petit ami…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA : Vous prévoyez de nous\n"
	.string "combattre ? Non, sauf si vous\p"
	.string "possédez deux POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY : Ma grande sœur est dure à\n"
	.string "POKéMON ! Ne pleure pas quand tu\p"
	.string "perds !$"

Route124_Text_RoyDefeat:
	.string "ROY : Uh-oh… Ma grande sœur va me\n"
	.string "mâcher…$"

Route124_Text_RoyPostBattle:
	.string "ROY : Ma grande sœur fait vraiment\n"
	.string "peur quand elle se met en colère.\p"
	.string "C'est pour ça qu'elle n'a pas de\n"
	.string "petit ami.$"

Route124_Text_LilaRoyRegister:
	.string "ROY : Allez-vous vous battre à\n"
	.string "nouveau avec nous ? Mais vas-y\p"
	.string "doucement la prochaine fois,\n"
	.string "d'accord ?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY : Vouliez-vous nous affronter ?\n"
	.string "Apportez deux POKéMON, alors.$"

Route124_Text_LilaRematchIntro:
	.string "LILA : Soupir… Me voilà dans la\n"
	.string "mer, mais qui est avec moi ? Mon\p"
	.string "petit frère! Oh, salut, ça fait\n"
	.string "longtemps. Battons-nous pour ne pas\p"
	.string "avoir à m'attarder sur les choses\n"
	.string "!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA : ROY ! C'est de ta faute si\n"
	.string "nous avons encore perdu ! Nous\p"
	.string "avons une séance d'entraînement\n"
	.string "plus tard !$"

Route124_Text_LilaPostRematch:
	.string "LILA : Soupir… Si j'avais un gentil\n"
	.string "petit-ami, nous battrions n'importe\p"
	.string "qui avec de jolies combinaisons…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA : Vous prévoyez de nous\n"
	.string "combattre ? Non, sauf si vous\p"
	.string "possédez deux POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY : Si nous perdons, je vais\n"
	.string "l'attraper. Je vais y aller à fond\p"
	.string "!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY : Uh-oh… Ma grande sœur va\n"
	.string "encore me gronder.$"

Route124_Text_RoyPostRematch:
	.string "ROY : Ma grande sœur fait vraiment\n"
	.string "peur quand elle se met en colère.\p"
	.string "Elle va me faire m'entraîner très\n"
	.string "dur avec POKéMON plus tard…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY : Vouliez-vous nous affronter ?\n"
	.string "Apportez deux POKéMON, alors.$"

Route124_Text_DeclanIntro:
	.string "Me voilà nageant seul sur cette mer\n"
	.string "large et belle. Il n'y a pas\p"
	.string "d'autre mot pour ça. C'est\n"
	.string "pathétique !$"

Route124_Text_DeclanDefeat:
	.string "Je me sens triste. Bleu comme le\n"
	.string "ciel…$"

Route124_Text_DeclanPostBattle:
	.string "Je devrais discuter avec les\n"
	.string "nageuses et les inviter à une\p"
	.string "longue baignade.$"

Route124_Text_IsabellaIntro:
	.string "Je ne vais pas perdre face à un\n"
	.string "DRESSEUR de surfeur.$"

Route124_Text_IsabellaDefeat:
	.string "Je n'ai que de la sueur dans les\n"
	.string "yeux ! Je ne pleure pas !$"

Route124_Text_IsabellaPostBattle:
	.string "Vous pouvez trouver de jolis\n"
	.string "fragments de choses colorés par\p"
	.string "ici.$"

Route125_Text_NolenIntro:
	.string "Je t'ai entendu approcher, alors je\n"
	.string "suis resté là pour toi !$"

Route125_Text_NolenDefeat:
	.string "Je me rends !$"

Route125_Text_NolenPostBattle:
	.string "Le son se propage plus rapidement\n"
	.string "dans l’eau que dans l’air.$"

Route125_Text_StanIntro:
	.string "Salut! Découvrez mon doux POKéMON\n"
	.string "!$"

Route125_Text_StanDefeat:
	.string "J'ai pataugé…$"

Route125_Text_StanPostBattle:
	.string "J'ai été époustouflée par le charme\n"
	.string "de HORSEA, alors j'ai aussi\p"
	.string "commencé à nager.$"

Route125_Text_TanyaIntro:
	.string "J'en ai marre de nager. Êtes-vous\n"
	.string "prêt à vous battre avec moi ?$"

Route125_Text_TanyaDefeat:
	.string "Tu es trop !$"

Route125_Text_TanyaPostBattle:
	.string "Ouf… Par quel chemin se trouve\n"
	.string "ALGATIA ?$"

Route125_Text_SharonIntro:
	.string "Aimeriez-vous affronter le POKéMON\n"
	.string "de type EAU que j'ai élevé ?$"

Route125_Text_SharonDefeat:
	.string "Je l'ai perdu…$"

Route125_Text_SharonPostBattle:
	.string "Votre pouvoir… Vous êtes la vraie\n"
	.string "affaire. Je suis étonné !$"

Route125_Text_ErnestIntro:
	.string "Ahah! Je suis un marin passionné et\n"
	.string "coriace ! J'ai bravé les mers du\p"
	.string "monde !$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar! Je ne pouvais pas gagner\n"
	.string "!$"

Route125_Text_ErnestPostBattle:
	.string "La marée monte et descend à\n"
	.string "l’intérieur de la GROTTE TREFONDS.\p"
	.string "À propos, il faut compter environ\n"
	.string "six heures entre la marée haute et\p"
	.string "la marée basse. Le saviez-vous ?$"

Route125_Text_ErnestRegister:
	.string "Enregistrez-moi dans votre POKéNAV\n"
	.string "et je vous dirai quelque chose de\p"
	.string "bien.$"

Route125_Text_ErnestRematchIntro:
	.string "Il est grand temps que je reçoive\n"
	.string "ma récompense de votre part !\p"
	.string "Allez, on se bat !$"

Route125_Text_ErnestRematchDefeat:
	.string "Je ne pouvais pas gagner ! Je ne\n"
	.string "pouvais absolument pas gagner !$"

Route125_Text_ErnestRematchPostBattle:
	.string "La GROTTE TREFONDS… Il y a des\n"
	.string "endroits accessibles ou non en\p"
	.string "fonction de la montée et de la\n"
	.string "descente de la marée. À propos, il\p"
	.string "faut compter environ six heures\n"
	.string "entre la marée haute et la marée\p"
	.string "basse. N'oubliez pas!$"

Route125_Text_KimIntro:
	.string "KIM : Un drôle de vieil homme vit\n"
	.string "dans la GROTTE TREFONDS. Quelqu'un\p"
	.string "m'a dit. Tu vas le voir aussi ?$"

Route125_Text_KimDefeat:
	.string "KIM : Je pensais que nous\n"
	.string "gagnerions.$"

Route125_Text_KimPostBattle:
	.string "KIM : Un drôle de vieil homme vit\n"
	.string "dans la GROTTE TREFONDS, n'est-ce\p"
	.string "pas ? Allons le voir, IRIS !$"

Route125_Text_KimNotEnoughMons:
	.string "KIM : Non, non, non ! Vous avez\n"
	.string "besoin de deux POKéMON, ou ce n'est\p"
	.string "tout simplement pas bon !$"

Route125_Text_IrisIntro:
	.string "IRIS : KIM, peux-tu me dire ce que\n"
	.string "nous cherchons ici ?$"

Route125_Text_IrisDefeat:
	.string "IRIS : Oh, nous nous sommes\n"
	.string "rapprochés.$"

Route125_Text_IrisPostBattle:
	.string "IRIS : KIM, on va vraiment dans la\n"
	.string "GROTTE TREFONDS ? Nous serons tous\p"
	.string "mouillés.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS : Oh, nous ne pourrions jamais\n"
	.string "faire quelque chose qui ressemble à\p"
	.string "une bataille à 2 contre 1.$"

Route125_Text_PresleyIntro:
	.string "Pourquoi un ORNISTE comme moi\n"
	.string "viendrait-il à la mer ?$"

Route125_Text_PresleyDefeat:
	.string "D'accord. Je vais vous dire\n"
	.string "pourquoi je suis ici.$"

Route125_Text_PresleyPostBattle:
	.string "J'ai mis un message dans une\n"
	.string "bouteille et je l'ai mis à la mer.\p"
	.string "Je suis sûr qu'une fille SWIMMER le\n"
	.string "trouvera !$"

Route125_Text_AuronIntro:
	.string "Hé! Est-ce que c'est toi qui jetais\n"
	.string "des ordures à la mer ?$"

Route125_Text_AuronDefeat:
	.string "Oh, tu ne jetais pas de déchets à\n"
	.string "la mer.$"

Route125_Text_AuronPostBattle:
	.string "J'ai trouvé plus tôt une bouteille\n"
	.string "disgracieuse qui flottait dans les\p"
	.string "vagues. Cela me met en colère que\n"
	.string "quelqu'un pollue la mer !$"

Route126_Text_BarryIntro:
	.string "La natation est un entraînement\n"
	.string "pour tout le corps ! Vous serez en\p"
	.string "forme !$"

Route126_Text_BarryDefeat:
	.string "Je l'admets! Vous gagnez !$"

Route126_Text_BarryPostBattle:
	.string "Grâce à ma routine quotidienne de\n"
	.string "natation… Regardez ! Régalez vos\p"
	.string "yeux de ce physique !$"

Route126_Text_DeanIntro:
	.string "Cette imposante montagne de roche\n"
	.string "blanche est ATALANOPOLIS.$"

Route126_Text_DeanDefeat:
	.string "J'en avais fini ?$"

Route126_Text_DeanPostBattle:
	.string "Je ne trouve pas l'entrée de\n"
	.string "SOOTOPOLIS. Où cela pourrait-il\p"
	.string "être ?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufufu ! Je suis en colère! $"

Route126_Text_NikkiDefeat:
	.string "Mon fantasme a éclaté comme s'il\n"
	.string "s'agissait d'une bulle ! Blub,\p"
	.string "blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Tu m'as battu… Je veux disparaître\n"
	.string "dans une vague de désespoir…$"

Route126_Text_BrendaIntro:
	.string "Bonjour, gamin ! Tu veux une\n"
	.string "bataille avec moi ?$"

Route126_Text_BrendaDefeat:
	.string "Oh, nooooh !$"

Route126_Text_BrendaPostBattle:
	.string "J'adore gambader avec POKéMON dans\n"
	.string "la mer comme ça !$"

Route126_Text_PabloIntro:
	.string "Découvrez ce corps sculpté! Je suis\n"
	.string "plus coupé qu'une CEINTURE NOIRE !$"

Route126_Text_PabloDefeat:
	.string "Oups ! Trop fort! Pas mal! Pas mal\n"
	.string "du tout !$"

Route126_Text_PabloPostBattle:
	.string "Perdre contre toi a stimulé mes\n"
	.string "sens ! Je vais m'entraîner plus\p"
	.string "fort, ainsi que POKéMON !$"

Route126_Text_PabloRegister:
	.string "Ouais, tu n'es pas mal du tout !\n"
	.string "J'aimerais mieux vous connaître !$"

Route126_Text_PabloRematchIntro:
	.string "Découvrez ce beau corps! Je suis\n"
	.string "plus galbée qu'un nageur !$"

Route126_Text_PabloRematchDefeat:
	.string "Oups ! Vraiment trop fort ! Pas\n"
	.string "mal! Pas mal du tout !$"

Route126_Text_PabloPostRematch:
	.string "Je vais m'entraîner encore plus dur\n"
	.string "! Vous êtes un grand motivateur !\p"
	.string "Vous devez revenir!$"

Route126_Text_LeonardoIntro:
	.string "Je ne savais même pas nager l'année\n"
	.string "dernière, mais maintenant je suis\p"
	.string "un bon NAGEUR. Je pense que je suis\n"
	.string "capable de tout maintenant.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, devenir gourmand n'a rien\n"
	.string "fait pour moi.$"

Route126_Text_LeonardoPostBattle:
	.string "Si vous vous entraînez dans quelque\n"
	.string "chose, vous vous améliorerez. Vous\p"
	.string "êtes jeune, n'ayez pas peur\n"
	.string "d'essayer toutes sortes de choses\p"
	.string "!$"

Route126_Text_IsobelIntro:
	.string "Si l'eau de mer vous monte dans le\n"
	.string "nez, n'est-ce pas terrible ?$"

Route126_Text_IsobelDefeat:
	.string "Acqu ! Pourquoi, toi… Glub !$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, je me suis étouffé avec de\n"
	.string "l'eau ! C'est amer ! C'est salé !!$"

Route126_Text_SiennaIntro:
	.string "J'y mets tout mon cœur !$"

Route126_Text_SiennaDefeat:
	.string "Tu avais plus de cœur !$"

Route126_Text_SiennaPostBattle:
	.string "J'ai besoin de me calmer\n"
	.string "maintenant… Je pense que je vais\p"
	.string "aller plonger.$"

Route127_Text_CamdenIntro:
	.string "Je peux le voir sur ton visage. Tu\n"
	.string "veux me défier.$"

Route127_Text_CamdenDefeat:
	.string "Waouh...$"

Route127_Text_CamdenPostBattle:
	.string "Un match bien joué me laisse\n"
	.string "rafraîchi et serein.$"

Route127_Text_DonnyIntro:
	.string "Avez-vous un rival contre lequel\n"
	.string "vous détestez perdre ?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh! Je déteste perdre !$"

Route127_Text_DonnyPostBattle:
	.string "Si vous avez un rival, n'avez-vous\n"
	.string "pas le sentiment que vous devez\p"
	.string "continuer à vous améliorer ?$"

Route127_Text_JonahIntro:
	.string "Grâce à la pêche, j'ai atteint un\n"
	.string "état de sérénité encalminée… S'il\p"
	.string "vous plaît, permettez-moi de\n"
	.string "démontrer…$"

Route127_Text_JonahDefeat:
	.string "Même si j'ai perdu, mon cœur reste\n"
	.string "calme…$"

Route127_Text_JonahPostBattle:
	.string "Peu importe que je n’attrape rien.\n"
	.string "La ligne reste dans l'eau…$"

Route127_Text_HenryIntro:
	.string "Oups ! Ne me dites pas que j'ai\n"
	.string "attrapé un POKéMON SURF ?$"

Route127_Text_HenryDefeat:
	.string "Je n'arrive pas à suivre !$"

Route127_Text_HenryPostBattle:
	.string "Ce serait une poignée si\n"
	.string "j'accrochais ton POKéMON coriace !$"

Route127_Text_RogerIntro:
	.string "Et bien Salut! C'est un match entre\n"
	.string "un fan de POKéMON et un passionné\p"
	.string "de pêche !$"

Route127_Text_RogerDefeat:
	.string "Non! Ma ligne est toute emmêlée !\n"
	.string "La fête est finie !$"

Route127_Text_RogerPostBattle:
	.string "Ma ligne de pêche danse ! Le tango\n"
	.string "enchevêtré ! Hahaha, grogne !$"

Route127_Text_AidanIntro:
	.string "Les POKéMON OISEAU ont une\n"
	.string "excellente vision. Ils repèrent\p"
	.string "leurs proies depuis de grandes\n"
	.string "hauteurs.$"

Route127_Text_AidanDefeat:
	.string "Ouf… j'abandonne.$"

Route127_Text_AidanPostBattle:
	.string "Il y a beaucoup de spots de plongée\n"
	.string "dans la mer par ici. Vous pouvez\p"
	.string "les repérer facilement depuis le\n"
	.string "ciel en raison de leur couleur plus\p"
	.string "foncée.$"

Route127_Text_KojiIntro:
	.string "Courez pieds nus. Cela renforcera\n"
	.string "vos semelles !$"

Route127_Text_KojiDefeat:
	.string "Ouah! J'ai un caillou sous l'ongle\n"
	.string "!$"

Route127_Text_KojiPostBattle:
	.string "Aller pieds nus, c'est génial. Mais\n"
	.string "vos CHAUSSURES DE RUNNING sont cool\p"
	.string "aussi.$"

Route127_Text_KojiRegister:
	.string "C'est ce que je fais aux gens qui\n"
	.string "me battent ! J'espère que nous\p"
	.string "pourrons recommencer.$"

Route127_Text_KojiRematchIntro:
	.string "Je cours toujours pieds nus\n"
	.string "quotidiennement. Mes semelles sont\p"
	.string "dures !$"

Route127_Text_KojiRematchDefeat:
	.string "Ouah! Des cailloux creusés dans mes\n"
	.string "arches !$"

Route127_Text_KojiPostRematch:
	.string "Envie de marcher pieds nus pendant\n"
	.string "un moment ? Pour que je puisse\p"
	.string "essayer tes CHAUSSURES DE RUNNING\n"
	.string "?$"

Route127_Text_AthenaIntro:
	.string "Nous devrions avoir un match lent\n"
	.string "et méthodique.$"

Route127_Text_AthenaDefeat:
	.string "Vous ne m'avez pas donné la chance\n"
	.string "d'élaborer une stratégie.$"

Route127_Text_AthenaPostBattle:
	.string "Quand je suis entouré par la mer et\n"
	.string "le ciel bleus, j'ai l'impression\p"
	.string "que le temps ralentit.$"

Route128_Text_IsaiahIntro:
	.string "GUIDOERNARA est encore loin…$"

Route128_Text_IsaiahDefeat:
	.string "Ma première victoire semble être\n"
	.string "loin aussi…$"

Route128_Text_IsaiahPostBattle:
	.string "Toute ma vie a été consacrée à la\n"
	.string "perte, mais je n'abandonnerai\p"
	.string "jamais !$"

Route128_Text_IsaiahRegister:
	.string "Je sais que je ne vais pas bien\n"
	.string "maintenant, mais je pense que je\p"
	.string "pourrai éventuellement gagner.\n"
	.string "Merci de m'inscrire dans votre\p"
	.string "POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "Je me sens toujours bien. Je\n"
	.string "continuerai à nager jusqu'à\p"
	.string "GUIDOERNARA.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Je n'ai pas encore goûté à ma\n"
	.string "première victoire…$"

Route128_Text_IsaiahPostRematch:
	.string "Je finirai par atteindre\n"
	.string "GUIDOERNARA où je pourrai\p"
	.string "éventuellement gagner…$"

Route128_Text_KatelynIntro:
	.string "Il faut nager, faire du vélo, puis\n"
	.string "courir un marathon dans un\p"
	.string "triathlon. C'est une course\n"
	.string "épuisante qui comprend trois\p"
	.string "épreuves.$"

Route128_Text_KatelynDefeat:
	.string "Une bataille POKéMON est également\n"
	.string "épuisante…$"

Route128_Text_KatelynPostBattle:
	.string "Je dois ensuite faire du VÉLO,\n"
	.string "mais… je suis sur le point de jeter\p"
	.string "l'éponge…$"

Route128_Text_KatelynRegister:
	.string "Eh bien, autant en tirer le\n"
	.string "meilleur parti. J'aimerais une\p"
	.string "revanche un jour.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triathlon, c'est long. Mais je\n"
	.string "suppose que le chemin pour devenir\p"
	.string "le CHAMPION POKéMON est aussi long\n"
	.string "et épuisant.$"

Route128_Text_KatelynRematchDefeat:
	.string "Une bataille POKéMON est vraiment\n"
	.string "dure et impitoyable…$"

Route128_Text_KatelynPostRematch:
	.string "Vous devriez réfléchir sérieusement\n"
	.string "aux défis sur ROUTE VICTOIRE.$"

Route128_Text_AlexaIntro:
	.string "Nous avons travaillé si dur pour\n"
	.string "monter un défi POKéMON LEAGUE… Nous\p"
	.string "ne pouvons pas nous permettre de\n"
	.string "perdre maintenant !$"

Route128_Text_AlexaDefeat:
	.string "Oh! Comment cela a-t-il pu arriver\n"
	.string "?!$"

Route128_Text_AlexaPostBattle:
	.string "Après tout ce que j'ai fait pour\n"
	.string "arriver ici, je n'abandonnerai pas\p"
	.string "après un revers.$"

Route128_Text_RubenIntro:
	.string "Il n'y a pas d'DRESSEUR plus fort\n"
	.string "que moi !$"

Route128_Text_RubenDefeat:
	.string "Ce n'est pas possible !$"

Route128_Text_RubenPostBattle:
	.string "Il n'y a probablement pas\n"
	.string "d'DRESSEUR plus fort que vous !$"

Route128_Text_WayneIntro:
	.string "Je veux visiter EVER GRANDE, alors\n"
	.string "je me suis attrapé un POKéMON qui\p"
	.string "connaît le mouvement CASCADE pour\n"
	.string "franchir les chutes.$"

Route128_Text_WayneDefeat:
	.string "Je suis découragé !$"

Route128_Text_WaynePostBattle:
	.string "Awww, putain ! Mon POKéMON connaît\n"
	.string "CASCADE, mais je n'ai pas le BADGE\p"
	.string "SOOTOPOLIS GYM !$"

Route128_Text_HarrisonIntro:
	.string "Vous avez l'air terriblement dur.\n"
	.string "Je me demande si je peux gagner ?$"

Route128_Text_HarrisonDefeat:
	.string "Aie! Je suppose qu'il était\n"
	.string "impossible de gagner.$"

Route128_Text_HarrisonPostBattle:
	.string "Il y a des DRESSEURS coriaces\n"
	.string "à gogo autour d’EVER GRANDE.\p"
	.string "Pensez-vous que je suis peut-être\n"
	.string "hors de ma ligue ?$"

Route128_Text_CarleeIntro:
	.string "La lumière du soleil semble être\n"
	.string "plus intense dans cette zone.$"

Route128_Text_CarleeDefeat:
	.string "Je ne voyais pas très bien à cause\n"
	.string "de l'éblouissement du soleil.$"

Route128_Text_CarleePostBattle:
	.string "Je devrais y retourner bientôt. Je\n"
	.string "dois réappliquer ma crème solaire.$"

Route129_Text_ChaseIntro:
	.string "C'est mon premier triathlon. Je\n"
	.string "suis tout tendu et nerveux !$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar ! Je n'ai pas réussi à\n"
	.string "gagner !$"

Route129_Text_ChasePostBattle:
	.string "Si je suis tout tendu, je ne\n"
	.string "pourrai pas tout donner.$"

Route129_Text_AllisonIntro:
	.string "Je suis au milieu d'un triathlon,\n"
	.string "mais bien sûr, pourquoi ne pas se\p"
	.string "battre ?$"

Route129_Text_AllisonDefeat:
	.string "J'étais sûr de gagner !$"

Route129_Text_AllisonPostBattle:
	.string "Savez-vous ce qu'il y a de mieux\n"
	.string "dans les triathlons ? Testez les\p"
	.string "limites de votre propre force et de\n"
	.string "votre endurance contre Mère Nature\p"
	.string "!$"

Route129_Text_ReedIntro:
	.string "Dis hé, hé ! Allons-y !$"

Route129_Text_ReedDefeat:
	.string "Battre, je suis battu. Ça y est,\n"
	.string "c'est fait !$"

Route129_Text_ReedPostBattle:
	.string "Il n'y a rien pour un perdant. Il\n"
	.string "est temps pour moi de rentrer chez\p"
	.string "moi.$"

Route129_Text_TishaIntro:
	.string "Qu'est-ce qui est pressé ? Allons-y\n"
	.string "doucement et doucement.$"

Route129_Text_TishaDefeat:
	.string "Oh mon. Je voulais me détendre un\n"
	.string "peu plus…$"

Route129_Text_TishaPostBattle:
	.string "Ne détestez-vous pas faire des\n"
	.string "erreurs lorsque vous êtes pressé ?\p"
	.string "C'est pourquoi j'essaie d'y aller\n"
	.string "lentement.$"

Route129_Text_ClarenceIntro:
	.string "Surfer n'est pas aussi facile qu'il\n"
	.string "y paraît, n'est-ce pas ?$"

Route129_Text_ClarenceDefeat:
	.string "Gagner n’est certainement pas\n"
	.string "facile.$"

Route129_Text_ClarencePostBattle:
	.string "Vous avez votre dévolu sur la\n"
	.string "POKéMON LEAGUE ? Continuez comme ça\p"
	.string "!$"

Route130_Text_RodneyIntro:
	.string "Quelle surprise! Je ne m'attendais\n"
	.string "pas à voir un DRESSEUR en mer. Je\p"
	.string "pense que nous devrions nous battre\n"
	.string "!$"

Route130_Text_RodneyDefeat:
	.string "Ce gamin est terriblement dur…$"

Route130_Text_RodneyPostBattle:
	.string "Vos yeux ont le regard de quelqu'un\n"
	.string "qui a vécu des défis difficiles et\p"
	.string "qui a gagné. Ça te va bien!$"

Route130_Text_KatieIntro:
	.string "Dans la mer d'un bleu profond, mon\n"
	.string "cœur bleu brisé trouve du réconfort\p"
	.string "parmi les vagues.$"

Route130_Text_KatieDefeat:
	.string "Comme la vaste mer bleue, le monde\n"
	.string "de POKéMON s'étend sur des\p"
	.string "profondeurs inimaginables.$"

Route130_Text_KatiePostBattle:
	.string "Les enfants du monde rêvent de\n"
	.string "devenir un jour le CHAMPION\p"
	.string "POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Flotter au large comme ça… C'est\n"
	.string "paisible.$"

Route130_Text_SantiagoDefeat:
	.string "J'avais besoin d'être un peu moins\n"
	.string "paisible !$"

Route130_Text_SantiagoPostBattle:
	.string "Nager et se battre comme ça… Je\n"
	.string "suis un gars heureux…$"

Route131_Text_RichardIntro:
	.string "La mer regorge de POKéMON. Ce n'est\n"
	.string "pas facile de nager, je vous le\p"
	.string "dis.$"

Route131_Text_RichardDefeat:
	.string "Les POKéMON élevés par les\n"
	.string "DRESSEURS sont vraiment\p"
	.string "coriaces…$"

Route131_Text_RichardPostBattle:
	.string "Halètement… Halètement… Je suis\n"
	.string "anéanti… Les choses sont faciles.\p"
	.string "C'est le départ qui est la partie\n"
	.string "la plus difficile. Aurai-je encore\p"
	.string "de l’énergie pour faire le voyage\n"
	.string "retour ?$"

Route131_Text_HermanIntro:
	.string "La mer… La mer… La mer… La mer à\n"
	.string "perte de vue ! J'en ai marre de la\p"
	.string "mer !$"

Route131_Text_HermanDefeat:
	.string "Bœuf !$"

Route131_Text_HermanPostBattle:
	.string "Je m'ennuie au bord de la mer, mais\n"
	.string "je dois nager. Je suis un nageur né\p"
	.string "! C'est ce que je suis.$"

Route131_Text_SusieIntro:
	.string "Salut, chérie, attends ! Nous\n"
	.string "devrions nous battre, toi et moi !$"

Route131_Text_SusieDefeat:
	.string "Tu es dur malgré ton apparence !$"

Route131_Text_SusiePostBattle:
	.string "Vous avez vu un gars là-bas qui se\n"
	.string "plaint d'en avoir marre de la mer ?\p"
	.string "Ce ne sont que des paroles. Il est\n"
	.string "désespérément amoureux de la mer !$"

Route131_Text_KaraIntro:
	.string "Pourquoi les hommes aiment-ils tant\n"
	.string "les maillots de bain ? Ils me\p"
	.string "lorgnent tous !$"

Route131_Text_KaraDefeat:
	.string "Je suis dépassé !$"

Route131_Text_KaraPostBattle:
	.string "Ce n'est peut-être pas mon maillot\n"
	.string "de bain qui fait paraître les\p"
	.string "hommes. Ça doit être ma beauté !$"

Route131_Text_ReliIntro:
	.string "RELI : Nous travaillerons ensemble\n"
	.string "en tant que frères et sœurs pour\p"
	.string "vous affronter !$"

Route131_Text_ReliDefeat:
	.string "RELI : Nous ne pouvions pas gagner\n"
	.string "même si nous travaillions\p"
	.string "ensemble…$"

Route131_Text_ReliPostBattle:
	.string "RELI : Les habitants de PACIFIDLOG\n"
	.string "sont avec la mer et POKéMON depuis\p"
	.string "leur naissance.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI : Tu n'as pas deux POKéMON ?\n"
	.string "Nous ne pouvons donc pas profiter\p"
	.string "d'une bataille.$"

Route131_Text_IanIntro:
	.string "IAN : Je fais de mon mieux avec ma\n"
	.string "sœur !$"

Route131_Text_IanDefeat:
	.string "IAN : J'ai fait de mon mieux avec\n"
	.string "ma sœur, mais nous n'avons toujours\p"
	.string "pas pu gagner…$"

Route131_Text_IanPostBattle:
	.string "IAN : Vous savez à quel point\n"
	.string "PACIFIDLOG est une ville flottante\p"
	.string "? Donc, partout où il y a la mer,\n"
	.string "elle fait partie de PACIFIDLOG !$"

Route131_Text_IanNotEnoughMons:
	.string "IAN : Si vous avez deux POKéMON, on\n"
	.string "vous affronte !$"

Route131_Text_TaliaIntro:
	.string "Si vous pouvez me battre, je vous\n"
	.string "donnerai d'excellentes informations\p"
	.string "!$"

Route131_Text_TaliaDefeat:
	.string "Oh? Ai-je perdu ?$"

Route131_Text_TaliaPostBattle:
	.string "Il y a un endroit étrange à\n"
	.string "proximité. Il y a une immense tour\p"
	.string "là-bas. Pourquoi n'irais-tu pas\n"
	.string "jeter un oeil ?$"

Route131_Text_KevinIntro:
	.string "Les gens de PACIFIDLOG forment un\n"
	.string "groupe pacifique. Ils ne se mettent\p"
	.string "jamais en colère. Cela vaut pour\n"
	.string "moi aussi.$"

Route131_Text_KevinDefeat:
	.string "Oups !$"

Route131_Text_KevinPostBattle:
	.string "Tch ! …Oh, attendez. Je ne suis pas\n"
	.string "en colère. Honnêtement! Mais, mon\p"
	.string "garçon, tu es fort ! Hahaha!$"

Route132_Text_GilbertIntro:
	.string "J'avais l'habitude d'attraper un\n"
	.string "rhume quand j'étais enfant, mais je\p"
	.string "suis devenue totalement en forme\n"
	.string "après avoir commencé à nager.$"

Route132_Text_GilbertDefeat:
	.string "J'ai envie de plus de puissance…$"

Route132_Text_GilbertPostBattle:
	.string "LES DRESSEURS parcourent les champs\n"
	.string "et les montagnes, ils doivent donc\p"
	.string "également être en forme.$"

Route132_Text_DanaIntro:
	.string "J'essaie de ne pas nager là où les\n"
	.string "courants sont trop forts.$"

Route132_Text_DanaDefeat:
	.string "Oh, s'il te plaît, non !$"

Route132_Text_DanaPostBattle:
	.string "Si je suis emporté, je perdrai tout\n"
	.string "mon sentiment d'appartenance…$"

Route132_Text_RonaldIntro:
	.string "Gagnez ou perdez, vous ne le saurez\n"
	.string "jamais tant que vous n'aurez pas\p"
	.string "essayé !$"

Route132_Text_RonaldDefeat:
	.string "Waah ! J'ai sombré dans la défaite\n"
	.string "!$"

Route132_Text_RonaldPostBattle:
	.string "Je ne me bats jamais quand je sais\n"
	.string "que je vais gagner. J'aime me\p"
	.string "battre sur le fil du rasoir, entre\n"
	.string "victoire et défaite !$"

Route132_Text_KiyoIntro:
	.string "Je contemple POKéMON 24h/24.\n"
	.string "Comment as-tu pu me battre ?$"

Route132_Text_KiyoDefeat:
	.string "J'ai perdu. Je reconnais ma\n"
	.string "défaite.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh… Vous êtes un fanatique de\n"
	.string "POKéMON, n'est-ce pas ? Vous devez\p"
	.string "contempler POKéMON 24 heures sur\n"
	.string "24, n'est-ce pas ?$"

Route132_Text_MakaylaIntro:
	.string "Je suis toujours avec mon mari,\n"
	.string "mais je peux gagner même sans lui.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, je suppose que je n'étais pas\n"
	.string "assez bon.$"

Route132_Text_MakaylaPostBattle:
	.string "Ce jeune homme là-bas ressemble à\n"
	.string "mon mari quand il était jeune. Il\p"
	.string "me fait rougir !$"

Route132_Text_JonathanIntro:
	.string "Quelqu'un me surveille\n"
	.string "attentivement. Était-ce toi ?$"

Route132_Text_JonathanDefeat:
	.string "Ouah! C'est plutôt fort, d'accord\n"
	.string "!$"

Route132_Text_JonathanPostBattle:
	.string "Je ne peux pas me débarrasser de ce\n"
	.string "sentiment que quelqu'un me\p"
	.string "surveille. Je n'arrive pas à me\n"
	.string "concentrer !$"

Route132_Text_PaxtonIntro:
	.string "Maintenant, où ma femme aurait-elle\n"
	.string "pu aller ? Je suis toujours avec\p"
	.string "elle. Je me demande si je peux\n"
	.string "gagner tout seul.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, je vois que je n'ai pas réussi\n"
	.string "à gagner tout seul finalement.$"

Route132_Text_PaxtonPostBattle:
	.string "Ma femme doit me chercher. Je\n"
	.string "ferais mieux d'aller la trouver\p"
	.string "tout de suite.$"

Route132_Text_DarcyIntro:
	.string "J’ai aimé m’entraîner ici seul.\n"
	.string "C'est affreux que tous ces gens\p"
	.string "soient venus !$"

Route132_Text_DarcyDefeat:
	.string "D'accord! Je ne me plaindrai pas de\n"
	.string "la présence d'autres personnes\p"
	.string "ici.$"

Route132_Text_DarcyPostBattle:
	.string "Je suppose que je peux m'associer à\n"
	.string "ce vieil homme et défier cette\p"
	.string "autre équipe.$"

Route133_Text_FranklinIntro:
	.string "Les courants vous ont-ils emporté\n"
	.string "ici aussi ? Cela devait être le\p"
	.string "destin. Battons-nous !$"

Route133_Text_FranklinDefeat:
	.string "Fort! Trop!$"

Route133_Text_FranklinPostBattle:
	.string "C'est juste ma chance qu'un\n"
	.string "DRESSEUR coriace comme toi dérive\p"
	.string "ici… Je dois être maudit…$"

Route133_Text_DebraIntro:
	.string "J'ai mené une vie de malheur et de\n"
	.string "misère… J'ai été rejeté, et c'est\p"
	.string "là que j'ai dérivé…$"

Route133_Text_DebraDefeat:
	.string "Une autre perte…$"

Route133_Text_DebraPostBattle:
	.string "Une vie à la dérive… Je n'en veux\n"
	.string "plus !$"

Route133_Text_LindaIntro:
	.string "Accueillir! Je t'attendais !$"

Route133_Text_LindaDefeat:
	.string "Non! S'il vous plaît !$"

Route133_Text_LindaPostBattle:
	.string "Un DRESSEUR d'enfant fort… C'est\n"
	.string "tellement ennuyeux !$"

Route133_Text_WarrenIntro:
	.string "Je veux gagner comme tout le monde,\n"
	.string "mais je ne relancerai pas POKéMON\p"
	.string "comme tout le monde.$"

Route133_Text_WarrenDefeat:
	.string "Mince! Mon chemin est encore trop\n"
	.string "mou !$"

Route133_Text_WarrenPostBattle:
	.string "C'est bien plus amusant de faire\n"
	.string "les choses comme je veux que d'être\p"
	.string "comme tout le monde. Je veux dire,\n"
	.string "c'est évident !$"

Route133_Text_BeckIntro:
	.string "Je suis venu jusqu'ici avec mon\n"
	.string "POKéMON OISEAU.$"

Route133_Text_BeckDefeat:
	.string "Toi… Tu es incroyablement cool !$"

Route133_Text_BeckPostBattle:
	.string "J'aimerais retourner à FORTREE,\n"
	.string "mais j'ai aussi appris à aimer cet\p"
	.string "endroit.$"

Route133_Text_MollieIntro:
	.string "J'ai dû me battre des milliers de\n"
	.string "fois. J'ai perdu le compte.$"

Route133_Text_MollieDefeat:
	.string "J'ai peut-être perdu des milliers\n"
	.string "de fois, mais une perte me fait\p"
	.string "toujours mal.$"

Route133_Text_MolliePostBattle:
	.string "Continue comme ça, mon jeune. Pour\n"
	.string "que tu puisses devenir comme mon\p"
	.string "mari et moi.$"

Route133_Text_ConorIntro:
	.string "Les jeunes sont trop heureux de\n"
	.string "suivre le courant. Ils sont sans\p"
	.string "direction.$"

Route133_Text_ConorDefeat:
	.string "Vous avez un but précis.$"

Route133_Text_ConorPostBattle:
	.string "Ne laissez pas les autres vous\n"
	.string "égarer. Ne perdez pas votre\p"
	.string "direction en vieillissant.$"

Route134_Text_JackIntro:
	.string "Même les POKéMON qui savent nager\n"
	.string "sont emportés par les courants\p"
	.string "rapides.$"

Route134_Text_JackDefeat:
	.string "Ayeeeeeh !$"

Route134_Text_JackPostBattle:
	.string "Je pense que POKéMON apprécie les\n"
	.string "courants rapides autour de ces\p"
	.string "régions.$"

Route134_Text_LaurelIntro:
	.string "Mon LUVDISC recherche un match\n"
	.string "amusant. Voulez-vous nous\p"
	.string "rejoindre?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "Il y a un collectionneur qui en\n"
	.string "veut aux BALANCES de LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okkeydokey! Assez de repos, gang !\n"
	.string "C'est l'heure du match !$"

Route134_Text_AlexDefeat:
	.string "Encore une fois à l'écart…$"

Route134_Text_AlexPostBattle:
	.string "Mon BIRD POKéMON se fatigue vite\n"
	.string "après un long vol…$"

Route134_Text_HitoshiIntro:
	.string "Vous êtes un DRESSEUR DE POKéMON.\n"
	.string "Pas besoin de mots. Nous nous\p"
	.string "battons maintenant.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … … … … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "C'est moi qui t'ai défié, et\n"
	.string "pourtant j'ai perdu. J'ai\p"
	.string "profondément honte…$"

Route134_Text_AaronIntro:
	.string "La marée sauvage dans cette région\n"
	.string "sert à nous rendre plus forts que\p"
	.string "jamais.$"

Route134_Text_AaronDefeat:
	.string "J'admets volontiers ma défaite.$"

Route134_Text_AaronPostBattle:
	.string "Nous reviendrons pour plus de\n"
	.string "formation à SITE MGUIDOEORE. Si tu\p"
	.string "le souhaites, tu devrais y aller\n"
	.string "aussi. Cela vous endurcira\p"
	.string "certainement !$"

Route134_Text_KelvinIntro:
	.string "O-notre bateau ! La marée l'a\n"
	.string "emporté !$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah ! S'il te plaît, arrête!\n"
	.string "S'il vous plaît !$"

Route134_Text_KelvinPostBattle:
	.string "Si nous ne pouvons pas SURFER,\n"
	.string "comment sommes-nous censés rentrer\p"
	.string "à la maison ? En fait, je sais\n"
	.string "qu'un POKéMON évanoui peut toujours\p"
	.string "SURFER, mais ça ne me semble pas\n"
	.string "bien.$"

Route134_Text_MarleyIntro:
	.string "Votre POKéMON pourra-t-il esquiver\n"
	.string "nos attaques ultra-rapides ?$"

Route134_Text_MarleyDefeat:
	.string "Je ne savais pas qu'une telle\n"
	.string "technique existait ! Vous nous avez\p"
	.string "complètement vaincus.$"

Route134_Text_MarleyPostBattle:
	.string "Je n'ai pas perdu ma passion pour\n"
	.string "la vitesse. Je vais essayer plus\p"
	.string "fort.$"

Route134_Text_ReynaIntro:
	.string "Mon POKéMON ne peut pas être\n"
	.string "démonté facilement !$"

Route134_Text_ReynaDefeat:
	.string "Vous plaisantez! Explique comment\n"
	.string "j'ai perdu !$"

Route134_Text_ReynaPostBattle:
	.string "Haha ! Vous avez gagné, d'accord !\n"
	.string "Je vais remonter en affrontant les\p"
	.string "DRESSEURS que je rencontre !$"

Route134_Text_HudsonIntro:
	.string "Écoute, as-tu vu un autre MARIN par\n"
	.string "ici ?$"

Route134_Text_HudsonDefeat:
	.string "Maintenant, c'est quelque chose !$"

Route134_Text_HudsonPostBattle:
	.string "Notre bateau a dérivé vers le\n"
	.string "large. Mon copain est un gars\p"
	.string "timide, donc je m'inquiète pour\n"
	.string "lui.$"
