RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "L'ÉCOLE DES FORMATTHIEUEURS est\n"
	.string "excellente. Si vous y étudiez, vous\p"
	.string "pourriez même devenir GYM LEADER.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "ROXANNE, la GYM LEADER, connaît\n"
	.string "vraiment beaucoup de choses sur\p"
	.string "POKéMON. Elle est vraiment forte\n"
	.string "aussi !$"
