gText_ObtainedTheItem::
	.string "{STR_VAR_2} obtenu!$"

gText_TheBagIsFull::
	.string "Le SAC est plein…$"

gText_PutItemInPocket::
	.string "{PLAYER} met {STR_VAR_2}\n"
	.string "dans POCHE {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} a trouvé {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Mince!\n"
	.string "Le SAC est plein…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} met {STR_VAR_2}\n"
	.string "dans le SAC.$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2} obtenu!$"

gText_NoRoomLeftForAnother::
	.string "Mince! Il n'y a plus de place\n"
	.string "pour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} a été transféré\n"
	.string "au PC.$"
