gText_WouldYouLikeToRestYourPkmn::
	.string "Bonjour! Bienvenue au CENTRE\n"
	.string "POKéMON.\p"
	.string "Nous pouvons soigner vos POKéMON\p"
	.string "Voulez-vous les soigner?$"

gText_IllTakeYourPkmn::
	.string "OK, je prends vos POKéMON un instant.$"

gText_RestoredPkmnToFullHealth::
	.string "Merci d'avoir attendu.\p"
	.string "Vos POKéMON sont en\n"
	.string "super forme.$"

gText_WeHopeToSeeYouAgain::
	.string "A une prochaine fois peut-être!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
