OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Lorsqu'une bataille POKéMON\n"
	.string "commence, celui à gauche de la\p"
	.string "liste disparaît en premier. Ainsi,\n"
	.string "lorsque vous avez plus de POKéMON\p"
	.string "dans votre groupe, essayez de\n"
	.string "changer l'ordre de vos POKéMON.\p"
	.string "Cela pourrait vous donner un\n"
	.string "avantage.$"
