AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
	.string "C'est un endroit parfait pour\n"
	.string "partir à la découverte ! C'est\p"
	.string "passionnant ici ! Je parie qu'il y\n"
	.string "a des trésors incroyables à bord.$"
