FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "En parlant de POKéDEXES, je me suis\n"
	.string "souvenu de quelque chose. J'ai\p"
	.string "rencontré ce DRESSEUR,\n"
	.string "PIERRE, alors que je cherchais des\p"
	.string "pierres rares. Hoo, mon garçon, il\n"
	.string "avait des POKéMON incroyables avec\p"
	.string "lui. Ils n’étaient pas seulement\n"
	.string "rares, ils étaient entraînés à des\p"
	.string "extrêmes terrifiants ! Il pourrait\n"
	.string "même être plus fort que le GYM\p"
	.string "LEADER de cette ville…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "C'est quoi ce truc que tu as là ? …\n"
	.string "… … … … … Oh, ça s'appelle un\p"
	.string "POKéDEX ? C'est vraiment génial !$"
