SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "Je vais vous montrer les sublimes\n"
	.string "techniques que j'ai apprises de\p"
	.string "notre LEADER JUAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "S'il te plaît, pardonne-moi, JUAN…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Regardez ce qui se passe si vous\n"
	.string "cassez tous les carreaux du sol.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Tu as fait tout ce chemin\n"
	.string "jusqu'ici, mais tu ne verras pas\p"
	.string "JUAN. Pas si tu perds contre moi,\n"
	.string "tu ne le feras pas !$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Vous êtes fort! J'ai été trompé par\n"
	.string "ton look mignon !$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Vous pourriez être assez bon pour\n"
	.string "éviter d'être anéanti d'un seul\p"
	.string "coup par JUAN.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "La vue de JUAN menant une bataille…\n"
	.string "La beauté même de celle-ci m'a\p"
	.string "poussé à devenir DRESSEUR.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Tu as combattu avec plus de beauté\n"
	.string "que je ne pouvais en rassembler…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "La grâce que vous apportez au\n"
	.string "combat est fabuleuse. Oh… j'ai\p"
	.string "tellement de chance d'avoir trouvé\n"
	.string "POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Je devrais t'apprendre à quel point\n"
	.string "les batailles peuvent être dures.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh. Tu es fort.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Je vais te dire quelque chose de\n"
	.string "bien. Si vous souhaitez atteindre\p"
	.string "JUAN, vous devez marcher une fois\n"
	.string "sur chaque carreau de sol.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "Le POKéMON GYM du plus haut niveau\n"
	.string "de la région HOENN… C'est le\p"
	.string "SOOTOPOLIS GYM.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Quel haut niveau tu es !$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "Plutôt que de vous contenter d’être\n"
	.string "dans un GYM fort, j’imagine que\p"
	.string "s’entraîner dans d’autres endroits\n"
	.string "vous rendra plus fort. Mais\p"
	.string "surtout, ça a l'air plus amusant.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "J'entraîne mon POKéMON avec JUAN.\n"
	.string "Ne pensez pas que je suis un jeu\p"
	.string "d'enfant.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "J'ai été battu…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Je pense que tu as du potentiel.\n"
	.string "Pourquoi ne restes-tu pas et ne\p"
	.string "t'entraînes-tu pas avec nous ?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Une glisse gracieuse sur la glace\n"
	.string "sans franchir aucune ligne… Un\p"
	.string "DRESSEUR réalisant cette\n"
	.string "performance serait d’une beauté\p"
	.string "élégante !$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Eh bien, excusez-moi ?!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "C'est vraiment évident, mais votre\n"
	.string "force en tant que DRESSEUR\p"
	.string "n'a rien à voir avec votre âge ou\n"
	.string "votre jeunesse.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Quand je suis avec mon POKéMON, le\n"
	.string "temps passe vite avant que tu\p"
	.string "puisses dire “ Oups ! ”$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Oups !$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "J'aimerais pouvoir oublier les\n"
	.string "causes perdues avant de pouvoir\p"
	.string "gérer un “ Oups ! ”$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Je peux combattre des POKéMON très\n"
	.string "rares si vous le souhaitez.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Oh, là maintenant ! Avez-vous bien\n"
	.string "regardé mon POKéMON ?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Je suis venu dans ce GYM parce que\n"
	.string "JUAN m'a félicité pour mon POKéMON\p"
	.string "chéri. Oh, si seulement j'avais\n"
	.string "rencontré JUAN il y a des années\p"
	.string "quand j'étais plus jeune…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Riez… Votre regard sombre est si\n"
	.string "charmant.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh cher. J'ai été beaucoup trop\n"
	.string "indulgent avec toi.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Vous ne pouviez pas mettre le doigt\n"
	.string "sur JUAN, j'en suis sûr. Rire…$"
