LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Les plus grands mystères de cette\n"
	.string "planète se trouvent au fond de la\p"
	.string "mer. Quelqu'un a dit ça, mais je ne\n"
	.string "sais pas…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Il y a une profonde tranchée\n"
	.string "sous-marine entre MOSSDEEP et\p"
	.string "SOOTOPOLIS. En tout cas, c'est ce\n"
	.string "que quelqu'un m'a dit.$"
